// ==========================================================
// 职业数据库
// 包含360个职业信息
// 生成时间: 2025-11-23
// ==========================================================

window.ProfessionsData = {
  // 职业分类配置（参考navConfig结构）
  categories: {
    tech: { name: '技术类', icon: '💻', color: 0x4285f4 },
    business: { name: '商业类', icon: '💼', color: 0x34a853 },
    creative: { name: '创意类', icon: '🎨', color: 0xea4335 },
    service: { name: '服务类', icon: '🤝', color: 0xfbbc04 },
    medical: { name: '医疗类', icon: '🏥', color: 0x673ab7 },
    education: { name: '教育类', icon: '📚', color: 0xff5722 },
    finance: { name: '金融类', icon: '💰', color: 0x009688 },
    management: { name: '管理类', icon: '👔', color: 0x795548 }
  },

  // 360个职业数据
  all: [
    // 技术类 (45个)
    { name: '软件工程师', category: 'tech', salary: '15-30K', hot: true },
    { name: '数据分析师', category: 'tech', salary: '12-25K', hot: true },
    { name: '前端开发', category: 'tech', salary: '12-28K', hot: true },
    { name: '后端开发', category: 'tech', salary: '15-30K', hot: true },
    { name: '测试工程师', category: 'tech', salary: '8-18K' },
    { name: '运维工程师', category: 'tech', salary: '10-22K' },
    { name: '算法工程师', category: 'tech', salary: '20-40K', hot: true },
    { name: '架构师', category: 'tech', salary: '30-60K', hot: true },
    { name: '网络工程师', category: 'tech', salary: '10-25K' },
    { name: '数据库管理员', category: 'tech', salary: '12-28K' },
    { name: '系统管理员', category: 'tech', salary: '10-22K' },
    { name: '技术支持', category: 'tech', salary: '8-18K' },
    { name: '安全工程师', category: 'tech', salary: '12-30K' },
    { name: '区块链开发', category: 'tech', salary: '25-50K', hot: true },
    { name: '云计算开发', category: 'tech', salary: '20-45K' },
    { name: '大数据开发', category: 'tech', salary: '20-45K' },
    { name: '机器学习', category: 'tech', salary: '25-60K', hot: true },
    { name: '深度学习', category: 'tech', salary: '30-70K' },
    { name: '自然语言', category: 'tech', salary: '25-60K' },
    { name: '计算机视觉', category: 'tech', salary: '25-60K' },
    { name: '推荐算法', category: 'tech', salary: '25-60K' },
    { name: '搜索算法', category: 'tech', salary: '25-60K' },
    { name: '广告算法', category: 'tech', salary: '25-60K' },
    { name: '风控算法', category: 'tech', salary: '25-60K' },
    { name: 'AI产品', category: 'tech', salary: '25-50K' },
    { name: '3D建模师', category: 'tech', salary: '12-30K' },
    { name: '渲染师', category: 'tech', salary: '15-35K' },
    { name: 'VR开发', category: 'tech', salary: '20-40K' },
    { name: 'AR开发', category: 'tech', salary: '20-40K' },
    { name: 'SEO优化', category: 'tech', salary: '10-25K' },
    { name: '录音师', category: 'tech', salary: '10-25K' },
    { name: '音响师', category: 'tech', salary: '10-25K' },
    { name: '灯光师', category: 'tech', salary: '10-25K' },
    { name: '特效师', category: 'tech', salary: '15-40K' },
    { name: '后期制作', category: 'tech', salary: '12-30K' },
    { name: '调色师', category: 'tech', salary: '15-35K' },
    { name: '剪辑师', category: 'tech', salary: '12-30K' },
    { name: '无人机飞手', category: 'tech', salary: '10-25K' },
    { name: '航拍摄影', category: 'tech', salary: '15-35K' },
    { name: '游戏程序', category: 'tech', salary: '15-40K' },
    { name: '硬件产品', category: 'tech', salary: '20-40K' },
    { name: '嵌入式开发', category: 'tech', salary: '15-35K' },
    { name: '移动开发', category: 'tech', salary: '15-35K' },
    { name: '全栈开发', category: 'tech', salary: '20-45K' },
    { name: 'DevOps工程师', category: 'tech', salary: '18-35K' },
    
    // 商业类 (45个)
    { name: '产品经理', category: 'business', salary: '15-35K', hot: true },
    { name: '项目经理', category: 'business', salary: '15-35K' },
    { name: '市场营销', category: 'business', salary: '8-20K' },
    { name: '销售经理', category: 'business', salary: '10-30K' },
    { name: '商务拓展', category: 'business', salary: '12-30K' },
    { name: '渠道经理', category: 'business', salary: '15-35K' },
    { name: '大客户经理', category: 'business', salary: '20-50K' },
    { name: '电话销售', category: 'business', salary: '6-15K' },
    { name: '零售店长', category: 'business', salary: '8-20K' },
    { name: '采购专员', category: 'business', salary: '8-18K' },
    { name: '采购经理', category: 'business', salary: '15-35K' },
    { name: '供应链', category: 'business', salary: '15-40K' },
    { name: '物流经理', category: 'business', salary: '15-35K' },
    { name: '仓储管理', category: 'business', salary: '10-25K' },
    { name: '配送管理', category: 'business', salary: '10-25K' },
    { name: '关务专员', category: 'business', salary: '10-25K' },
    { name: '外贸专员', category: 'business', salary: '10-30K' },
    { name: '跨境电商', category: 'business', salary: '10-30K', hot: true },
    { name: '独立站', category: 'business', salary: '12-35K' },
    { name: '亚马逊运营', category: 'business', salary: '10-30K' },
    { name: '速卖通运营', category: 'business', salary: '10-25K' },
    { name: 'Lazada运营', category: 'business', salary: '10-25K' },
    { name: 'Shopee运营', category: 'business', salary: '10-25K' },
    { name: 'Wish运营', category: 'business', salary: '10-25K' },
    { name: 'eBay运营', category: 'business', salary: '10-25K' },
    { name: '阿里国际', category: 'business', salary: '10-30K' },
    { name: '1688运营', category: 'business', salary: '8-20K' },
    { name: '拼多多运营', category: 'business', salary: '10-25K' },
    { name: '京东运营', category: 'business', salary: '10-25K' },
    { name: '天猫运营', category: 'business', salary: '12-30K' },
    { name: '淘宝运营', category: 'business', salary: '10-25K' },
    { name: '直播带货', category: 'business', salary: '15-100K', hot: true },
    { name: '社群团购', category: 'business', salary: '10-30K' },
    { name: '社区团购', category: 'business', salary: '10-30K' },
    { name: '团长', category: 'business', salary: '8-20K' },
    { name: '地推专员', category: 'business', salary: '8-20K' },
    { name: '校园代理', category: 'business', salary: '5-15K' },
    { name: '校园大使', category: 'business', salary: '3-8K' },
    { name: '房地产经纪', category: 'business', salary: '10-50K' },
    { name: '招商经理', category: 'business', salary: '15-40K' },
    { name: '商场管理', category: 'business', salary: '15-35K' },
    { name: '品类管理', category: 'business', salary: '12-30K' },
    { name: '经销商', category: 'business', salary: '10-50K' },
    { name: '批发商', category: 'business', salary: '15-60K' },
    { name: '零售商', category: 'business', salary: '10-40K' },
    { name: '贸易专员', category: 'business', salary: '12-35K' },
    
    // 创意类 (45个)
    { name: 'UI设计师', category: 'creative', salary: '10-20K', hot: true },
    { name: '平面设计', category: 'creative', salary: '8-20K' },
    { name: '网页设计', category: 'creative', salary: '10-25K' },
    { name: '游戏设计', category: 'creative', salary: '12-30K' },
    { name: '动画设计', category: 'creative', salary: '10-28K' },
    { name: '服装设计', category: 'creative', salary: '10-25K' },
    { name: '珠宝设计', category: 'creative', salary: '12-30K' },
    { name: '工业设计', category: 'creative', salary: '12-35K' },
    { name: '建筑设计', category: 'creative', salary: '15-40K' },
    { name: '景观设计', category: 'creative', salary: '12-30K' },
    { name: '城市规划', category: 'creative', salary: '15-35K' },
    { name: '室内设计', category: 'creative', salary: '10-25K' },
    { name: '装修设计', category: 'creative', salary: '10-30K' },
    { name: '交互设计', category: 'creative', salary: '15-35K' },
    { name: '用户体验', category: 'creative', salary: '15-40K' },
    { name: '插画师', category: 'creative', salary: '8-25K' },
    { name: '漫画家', category: 'creative', salary: '10-30K' },
    { name: '作家', category: 'creative', salary: '8-30K' },
    { name: '编剧', category: 'creative', salary: '10-40K' },
    { name: '导演', category: 'creative', salary: '20-80K' },
    { name: '演员', category: 'creative', salary: '10-100K' },
    { name: '歌手', category: 'creative', salary: '10-100K' },
    { name: '音乐制作人', category: 'creative', salary: '15-50K' },
    { name: 'DJ', category: 'creative', salary: '10-30K' },
    { name: '舞蹈演员', category: 'creative', salary: '8-25K' },
    { name: '模特', category: 'creative', salary: '10-50K' },
    { name: '摄影师', category: 'creative', salary: '8-25K' },
    { name: '摄像师', category: 'creative', salary: '10-30K' },
    { name: '化妆师', category: 'creative', salary: '8-25K' },
    { name: '化妆造型', category: 'creative', salary: '10-30K' },
    { name: '纹身师', category: 'creative', salary: '10-40K' },
    { name: '花艺师', category: 'creative', salary: '8-20K' },
    { name: '游戏美术', category: 'creative', salary: '12-30K' },
    { name: '游戏策划', category: 'creative', salary: '15-35K' },
    { name: '美术指导', category: 'creative', salary: '20-45K' },
    { name: '艺术总监', category: 'creative', salary: '20-45K' },
    { name: '创意总监', category: 'creative', salary: '20-50K' },
    { name: '文案策划', category: 'creative', salary: '8-20K' },
    { name: '创意文案', category: 'creative', salary: '10-25K' },
    { name: '道具师', category: 'creative', salary: '8-20K' },
    { name: '服装师', category: 'creative', salary: '8-20K' },
    { name: '设计师助理', category: 'creative', salary: '6-15K' },
    { name: '美术编辑', category: 'creative', salary: '8-18K' },
    { name: '视觉设计', category: 'creative', salary: '10-25K' },
    { name: '品牌设计', category: 'creative', salary: '12-30K' },
    { name: '包装设计', category: 'creative', salary: '10-25K' },
    
    // 服务类 (45个)
    { name: '客服代表', category: 'service', salary: '5-10K' },
    { name: '行政助理', category: 'service', salary: '5-12K' },
    { name: '人力资源', category: 'service', salary: '8-18K' },
    { name: '售前工程师', category: 'service', salary: '12-30K' },
    { name: '售后工程师', category: 'service', salary: '8-20K' },
    { name: '快递员', category: 'service', salary: '6-15K' },
    { name: '外卖骑手', category: 'service', salary: '6-12K' },
    { name: '仓库管理员', category: 'service', salary: '5-10K' },
    { name: '保安', category: 'service', salary: '4-8K' },
    { name: '保洁员', category: 'service', salary: '3-6K' },
    { name: '保姆', category: 'service', salary: '5-12K' },
    { name: '月嫂', category: 'service', salary: '8-20K' },
    { name: '护工', category: 'service', salary: '5-10K' },
    { name: '钟点工', category: 'service', salary: '4-8K' },
    { name: '家教', category: 'service', salary: '8-25K' },
    { name: '翻译', category: 'service', salary: '10-30K' },
    { name: '同声传译', category: 'service', salary: '30-80K' },
    { name: '导游', category: 'service', salary: '6-20K' },
    { name: '旅行社经理', category: 'service', salary: '12-30K' },
    { name: '酒店经理', category: 'service', salary: '15-35K' },
    { name: '空乘', category: 'service', salary: '10-25K' },
    { name: '迎宾员', category: 'service', salary: '4-8K' },
    { name: '门童', category: 'service', salary: '4-8K' },
    { name: '行李员', category: 'service', salary: '4-7K' },
    { name: '泊车员', category: 'service', salary: '5-10K' },
    { name: '婚礼策划', category: 'service', salary: '10-30K' },
    { name: '活动执行', category: 'service', salary: '8-18K' },
    { name: '礼仪小姐', category: 'service', salary: '5-12K' },
    { name: '美容师', category: 'service', salary: '6-18K' },
    { name: '美发师', category: 'service', salary: '6-20K' },
    { name: '美甲师', category: 'service', salary: '6-15K' },
    { name: '美睫师', category: 'service', salary: '8-20K' },
    { name: '纹绣师', category: 'service', salary: '10-30K' },
    { name: '足疗师', category: 'service', salary: '6-15K' },
    { name: '按摩师', category: 'service', salary: '6-18K' },
    { name: '推拿师', category: 'service', salary: '8-20K' },
    { name: '健身教练', category: 'service', salary: '8-20K' },
    { name: '瑜伽教练', category: 'service', salary: '10-25K' },
    { name: '游泳教练', category: 'service', salary: '10-25K' },
    { name: '舞蹈教练', category: 'service', salary: '10-25K' },
    { name: '私人教练', category: 'service', salary: '12-30K' },
    { name: '生活管家', category: 'service', salary: '8-20K' },
    { name: '家政服务', category: 'service', salary: '6-15K' },
    { name: '宠物美容', category: 'service', salary: '6-18K' },
    { name: '宠物护理', category: 'service', salary: '5-12K' },
    
    // 医疗类 (45个)
    { name: '医生', category: 'medical', salary: '10-40K', hot: true },
    { name: '护士', category: 'medical', salary: '6-15K' },
    { name: '药剂师', category: 'medical', salary: '8-20K' },
    { name: '兽医', category: 'medical', salary: '10-30K' },
    { name: '牙医', category: 'medical', salary: '20-50K' },
    { name: '中医师', category: 'medical', salary: '15-40K' },
    { name: '康复治疗师', category: 'medical', salary: '8-20K' },
    { name: '检验师', category: 'medical', salary: '8-18K' },
    { name: '医学影像', category: 'medical', salary: '10-25K' },
    { name: '营养师', category: 'medical', salary: '10-30K' },
    { name: '心理咨询师', category: 'medical', salary: '15-40K' },
    { name: '验光师', category: 'medical', salary: '8-20K' },
    { name: '配镜师', category: 'medical', salary: '6-15K' },
    { name: '助听器验配', category: 'medical', salary: '8-18K' },
    { name: '康复师', category: 'medical', salary: '10-25K' },
    { name: '针灸师', category: 'medical', salary: '12-30K' },
    { name: '理疗师', category: 'medical', salary: '8-20K' },
    { name: '口腔医生', category: 'medical', salary: '15-40K' },
    { name: '眼科医生', category: 'medical', salary: '15-40K' },
    { name: '外科医生', category: 'medical', salary: '20-50K' },
    { name: '内科医生', category: 'medical', salary: '15-40K' },
    { name: '儿科医生', category: 'medical', salary: '15-40K' },
    { name: '妇科医生', category: 'medical', salary: '15-40K' },
    { name: '产科医生', category: 'medical', salary: '18-45K' },
    { name: '急诊医生', category: 'medical', salary: '18-45K' },
    { name: '麻醉医生', category: 'medical', salary: '20-50K' },
    { name: '病理医生', category: 'medical', salary: '15-40K' },
    { name: '放射科医生', category: 'medical', salary: '15-40K' },
    { name: '超声科医生', category: 'medical', salary: '12-35K' },
    { name: '核医学医生', category: 'medical', salary: '18-45K' },
    { name: '全科医生', category: 'medical', salary: '12-35K' },
    { name: '家庭医生', category: 'medical', salary: '15-40K' },
    { name: '公卫医生', category: 'medical', salary: '10-30K' },
    { name: '防疫医生', category: 'medical', salary: '10-30K' },
    { name: '体检医生', category: 'medical', salary: '10-25K' },
    { name: '美容医生', category: 'medical', salary: '20-60K' },
    { name: '整形医生', category: 'medical', salary: '25-80K' },
    { name: '皮肤科医生', category: 'medical', salary: '15-40K' },
    { name: '性病科医生', category: 'medical', salary: '15-40K' },
    { name: '传染科医生', category: 'medical', salary: '15-40K' },
    { name: '肿瘤科医生', category: 'medical', salary: '20-60K' },
    { name: '心血管医生', category: 'medical', salary: '20-60K' },
    { name: '神经科医生', category: 'medical', salary: '20-60K' },
    { name: '精神科医生', category: 'medical', salary: '15-45K' },
    { name: '法医', category: 'medical', salary: '15-40K' },
    
    // 教育类 (45个)
    { name: '教师', category: 'education', salary: '6-15K' },
    { name: '大学教师', category: 'education', salary: '10-30K' },
    { name: '中小学教师', category: 'education', salary: '6-15K' },
    { name: '培训师', category: 'education', salary: '15-40K' },
    { name: '课程顾问', category: 'education', salary: '8-20K' },
    { name: '教务管理', category: 'education', salary: '8-18K' },
    { name: '图书管理员', category: 'education', salary: '5-12K' },
    { name: '外语教师', category: 'education', salary: '10-25K' },
    { name: '在线教师', category: 'education', salary: '10-30K' },
    { name: '幼教老师', category: 'education', salary: '5-12K' },
    { name: '早教老师', category: 'education', salary: '6-15K' },
    { name: '特教老师', category: 'education', salary: '8-20K' },
    { name: '音乐老师', category: 'education', salary: '8-20K' },
    { name: '美术老师', category: 'education', salary: '8-20K' },
    { name: '体育老师', category: 'education', salary: '7-18K' },
    { name: '舞蹈老师', category: 'education', salary: '8-20K' },
    { name: '书法老师', category: 'education', salary: '8-20K' },
    { name: '围棋老师', category: 'education', salary: '10-25K' },
    { name: '象棋老师', category: 'education', salary: '8-20K' },
    { name: '编程老师', category: 'education', salary: '15-35K' },
    { name: '机器人老师', category: 'education', salary: '12-30K' },
    { name: '科学老师', category: 'education', salary: '8-20K' },
    { name: '数学老师', category: 'education', salary: '8-20K' },
    { name: '物理老师', category: 'education', salary: '8-20K' },
    { name: '化学老师', category: 'education', salary: '8-20K' },
    { name: '生物老师', category: 'education', salary: '8-20K' },
    { name: '历史老师', category: 'education', salary: '7-18K' },
    { name: '地理老师', category: 'education', salary: '7-18K' },
    { name: '政治老师', category: 'education', salary: '7-18K' },
    { name: '语文老师', category: 'education', salary: '7-18K' },
    { name: '英语老师', category: 'education', salary: '8-22K' },
    { name: '日语老师', category: 'education', salary: '10-25K' },
    { name: '韩语老师', category: 'education', salary: '10-25K' },
    { name: '法语老师', category: 'education', salary: '12-30K' },
    { name: '德语老师', category: 'education', salary: '12-30K' },
    { name: '西班牙语老师', category: 'education', salary: '12-30K' },
    { name: '雅思老师', category: 'education', salary: '15-40K' },
    { name: '托福老师', category: 'education', salary: '15-40K' },
    { name: 'GRE老师', category: 'education', salary: '18-45K' },
    { name: 'GMAT老师', category: 'education', salary: '18-45K' },
    { name: '考研老师', category: 'education', salary: '15-40K' },
    { name: '公务员老师', category: 'education', salary: '12-35K' },
    { name: '职业导师', category: 'education', salary: '15-40K' },
    { name: '企业培训师', category: 'education', salary: '20-50K' },
    
    // 金融类 (45个)
    { name: '投资顾问', category: 'finance', salary: '20-50K' },
    { name: '理财规划师', category: 'finance', salary: '15-35K' },
    { name: '保险代理人', category: 'finance', salary: '8-30K' },
    { name: '信贷专员', category: 'finance', salary: '10-25K' },
    { name: '审计师', category: 'finance', salary: '12-30K' },
    { name: '税务专员', category: 'finance', salary: '10-25K' },
    { name: '成本会计', category: 'finance', salary: '8-18K' },
    { name: '出纳员', category: 'finance', salary: '5-10K' },
    { name: '财务会计', category: 'finance', salary: '7-15K' },
    { name: '量化分析', category: 'finance', salary: '30-100K', hot: true },
    { name: '量化交易', category: 'finance', salary: '30-150K' },
    { name: '金融科技', category: 'finance', salary: '20-50K' },
    { name: '支付产品', category: 'finance', salary: '20-45K' },
    { name: '信贷产品', category: 'finance', salary: '20-45K' },
    { name: '理财经理', category: 'finance', salary: '15-40K' },
    { name: '私人银行', category: 'finance', salary: '30-80K' },
    { name: '投资银行', category: 'finance', salary: '40-150K' },
    { name: '风险投资', category: 'finance', salary: '50-200K' },
    { name: '私募股权', category: 'finance', salary: '50-200K' },
    { name: '基金管理', category: 'finance', salary: '30-100K' },
    { name: '证券分析', category: 'finance', salary: '20-50K' },
    { name: '期货交易', category: 'finance', salary: '20-60K' },
    { name: '外汇交易', category: 'finance', salary: '20-60K' },
    { name: '保险精算', category: 'finance', salary: '25-60K' },
    { name: '再保险', category: 'finance', salary: '30-70K' },
    { name: '保险理赔', category: 'finance', salary: '10-25K' },
    { name: '保险销售', category: 'finance', salary: '8-30K' },
    { name: '风控专员', category: 'finance', salary: '12-30K' },
    { name: '合规专员', category: 'finance', salary: '12-30K' },
    { name: '反洗钱专员', category: 'finance', salary: '15-35K' },
    { name: '信用分析师', category: 'finance', salary: '15-35K' },
    { name: '行业研究员', category: 'finance', salary: '20-50K' },
    { name: '策略分析师', category: 'finance', salary: '25-60K' },
    { name: '投资经理', category: 'finance', salary: '25-60K' },
    { name: '资产管理', category: 'finance', salary: '20-50K' },
    { name: '财富管理', category: 'finance', salary: '25-60K' },
    { name: '家族办公室', category: 'finance', salary: '40-120K' },
    { name: '信托经理', category: 'finance', salary: '30-80K' },
    { name: '租赁经理', category: 'finance', salary: '15-40K' },
    { name: '保理业务', category: 'finance', salary: '15-40K' },
    { name: '票据业务', category: 'finance', salary: '12-35K' },
    { name: '结算专员', category: 'finance', salary: '10-25K' },
    { name: '清算专员', category: 'finance', salary: '10-25K' },
    { name: '资金管理', category: 'finance', salary: '20-50K' },
    { name: ' treasury', category: 'finance', salary: '25-60K' },
    
    // 管理类 (45个)
    { name: '人力资源总监', category: 'management', salary: '25-50K' },
    { name: '财务总监', category: 'management', salary: '30-80K' },
    { name: '技术总监', category: 'management', salary: '40-100K' },
    { name: '运营总监', category: 'management', salary: '25-60K' },
    { name: '市场总监', category: 'management', salary: '25-60K' },
    { name: '销售总监', category: 'management', salary: '30-80K' },
    { name: 'CEO', category: 'management', salary: '50-200K' },
    { name: 'COO', category: 'management', salary: '40-150K' },
    { name: 'CTO', category: 'management', salary: '40-150K' },
    { name: 'CFO', category: 'management', salary: '40-150K' },
    { name: 'CMO', category: 'management', salary: '35-120K' },
    { name: 'CHO', category: 'management', salary: '30-100K' },
    { name: 'CIO', category: 'management', salary: '35-120K' },
    { name: 'CSO', category: 'management', salary: '35-120K' },
    { name: 'CKO', category: 'management', salary: '30-100K' },
    { name: 'CPO', category: 'management', salary: '35-120K' },
    { name: '合伙人', category: 'management', salary: '50-300K' },
    { name: '创业者', category: 'management', salary: '0-500K' },
    { name: '总经理', category: 'management', salary: '30-100K' },
    { name: '副总经理', category: 'management', salary: '25-80K' },
    { name: '部门经理', category: 'management', salary: '20-60K' },
    { name: '团队主管', category: 'management', salary: '15-40K' },
    { name: '项目经理', category: 'management', salary: '15-35K' },
    { name: '产品总监', category: 'management', salary: '30-80K' },
    { name: '设计总监', category: 'management', salary: '25-50K' },
    { name: '研发总监', category: 'management', salary: '35-100K' },
    { name: '质量总监', category: 'management', salary: '25-60K' },
    { name: '生产总监', category: 'management', salary: '25-60K' },
    { name: '采购总监', category: 'management', salary: '25-60K' },
    { name: '物流总监', category: 'management', salary: '25-60K' },
    { name: '供应链总监', category: 'management', salary: '30-80K' },
    { name: '品牌总监', category: 'management', salary: '30-70K' },
    { name: '营销总监', category: 'management', salary: '30-70K' },
    { name: '渠道总监', category: 'management', salary: '30-70K' },
    { name: '商务总监', category: 'management', salary: '30-70K' },
    { name: '战略总监', category: 'management', salary: '35-100K' },
    { name: '投资总监', category: 'management', salary: '40-120K' },
    { name: '风控总监', category: 'management', salary: '35-100K' },
    { name: '法务总监', category: 'management', salary: '35-100K' },
    { name: '合规总监', category: 'management', salary: '35-100K' },
    { name: '行政总监', category: 'management', salary: '20-50K' },
    { name: '信息总监', category: 'management', salary: '30-80K' },
    { name: '数据总监', category: 'management', salary: '35-100K' },
    { name: '创新总监', category: 'management', salary: '30-80K' }
  ],

  // 获取方法
  getProfessionsByCategory(category) {
    return this.all.filter(p => p.category === category);
  },
  
  getHotProfessions() {
    return this.all.filter(p => p.hot);
  },
  
  getRandomProfessions(count = 20) {
    const shuffled = [...this.all].sort(() => 0.5 - Math.random());
    return shuffled.slice(0, count);
  },
  
  searchProfessions(keyword) {
    return this.all.filter(p => 
      p.name.toLowerCase().includes(keyword.toLowerCase())
    );
  }
};

// 数据加载完成标记
window.ProfessionsDataLoaded = true;
