/**
 * ESP32 AT 指令配置文件
 * 所有指令数据集中于此，方便维护和扩展。
 */
window.atCommandConfig = {
    "基础指令": [
        { name: 'AT', desc: '测试 AT 启动' },
        { name: 'AT+RST', desc: '重启模块' },
        { name: 'AT+GMR', desc: '查询版本信息' },
        { name: 'AT+GSLP', desc: '进入 Deep-sleep 模式' },
        { name: 'ATE', desc: '开关回显功能' },
        { name: 'AT+RESTORE', desc: '恢复出厂设置' },
        { name: 'AT+UART_CUR', desc: '设置 UART 当前临时设置（不保存）' },
        { name: 'AT+UART_DEF', desc: '设置 UART 默认配置（保存到 Flash）' },
        { name: 'AT+SLEEP', desc: '设置 sleep 模式' },
        { name: 'AT+SYSRAM', desc: '查询当前剩余 RAM 大小' },
        { name: 'AT+SYSFLASH', desc: '读写 Flash 用户分区' },
        { name: 'AT+FS', desc: '文件系统操作' },
        { name: 'AT+RFPOWER', desc: '设置 RF TX Power' }
    ],
    "Wi-Fi功能": [
        { name: 'AT+CWMODE', desc: '设置 Wi-Fi 模式' },
        { name: 'AT+CWJAP', desc: '连接 AP' },
        { name: 'AT+CWLAPOPT', desc: '设置 CWLAP 指令的属性' },
        { name: 'AT+CWLAP', desc: '扫描当前可用的 AP' },
        { name: 'AT+CWQAP', desc: '断开与 AP 的连接' },
        { name: 'AT+CWSAP', desc: '配置 ESP32 SoftAP 参数' },
        { name: 'AT+CWLIF', desc: '查询连接到 ESP32 SoftAP 的 Station 信息' },
        { name: 'AT+CWDHCP', desc: '设置 DHCP' },
        { name: 'AT+CWDHCPS', desc: '设置 SoftAP DHCP 分配的 IP 范围' },
        { name: 'AT+CWAUTOCONN', desc: '设置上电是否自动连接 AP' },
        { name: 'AT+CWSTARTSMART', desc: '开启 SmartConfig' },
        { name: 'AT+CWSTOPSMART', desc: '停止 SmartConfig' },
        { name: 'AT+WPS', desc: '设置 WPS 功能' },
        { name: 'AT+CWHOSTNAME', desc: '设置 Station 的主机名称' },
        { name: 'AT+MDNS', desc: '设置 MDNS 功能' }
    ],
    "TCP/IP工具": [
        { name: 'AT+CIPSTATUS', desc: '查询网络连接信息' },
        { name: 'AT+CIPDOMAIN', desc: '域名解析功能' },
        { name: 'AT+CIPDNS', desc: '自定义 DNS 服务器' },
        { name: 'AT+CIPSTAMAC', desc: '设置 ESP32 Station 的 MAC 地址' },
        { name: 'AT+CIPAPMAC', desc: '设置 ESP32 SoftAP 的 MAC 地址' },
        { name: 'AT+CIPSTA', desc: '设置 ESP32 Station 的 IP 地址' },
        { name: 'AT+CIPAP', desc: '设置 ESP32 SoftAP 的 IP 地址' },
        { name: 'AT+CIPSTART', desc: '建立 TCP/UDP/SSL 连接' },
        { name: 'AT+CIPSSLCCONF', desc: '配置 SSL Client' },
        { name: 'AT+CIPSEND', desc: '发送数据' },
        { name: 'AT+CIPSENDEX', desc: '发送数据（遇\\0结束）' },
        { name: 'AT+CIPCLOSE', desc: '关闭 TCP/UDP/SSL 传输' },
        { name: 'AT+CIFSR', desc: '查询本地 IP 地址' },
        { name: 'AT+CIPMUX', desc: '设置多连接' },
        { name: 'AT+CIPSERVER', desc: '建立/关闭 TCP 或 SSL 服务器' },
        { name: 'AT+CIPSERVERMAXCONN', desc: '设置服务器允许的最大连接数' },
        { name: 'AT+CIPMODE', desc: '设置传输模式（透传）' },
        { name: 'AT+SAVETRANSLINK', desc: '保存透传到 Flash' },
        { name: 'AT+CIPSTO', desc: '设置 TCP 服务器超时时间' },
        { name: 'AT+CIPSNTPCFG', desc: '设置时域和 SNTP 服务器' },
        { name: 'AT+CIPSNTPTIME', desc: '查询 SNTP 时间' },
        { name: 'AT+CIUPDATE', desc: '通过 Wi-Fi 升级软件' },
        { name: 'AT+CIPDINFO', desc: '接收网络数据时是否提示对端 IP 和端口' },
        { name: 'AT+PING', desc: 'Ping 功能' }
    ],
    "BLE蓝牙": [
        { name: 'AT+BLEINIT', desc: 'BLE 初始化' },
        { name: 'AT+BLEADDR', desc: '设置 BLE 设备地址' },
        { name: 'AT+BLENAME', desc: '设置 BLE 设备名称' },
        { name: 'AT+BLESCANPARAM', desc: '设置 BLE 扫描参数' },
        { name: 'AT+BLESCAN', desc: '使能 BLE 扫描' },
        { name: 'AT+BLESCANRSPDATA', desc: '设置 BLE 扫描响应' },
        { name: 'AT+BLEADVPARAM', desc: '设置广播参数' },
        { name: 'AT+BLEADVDATA', desc: '设置 BLE 广播数据' },
        { name: 'AT+BLEADVSTART', desc: '开始 BLE 广播' },
        { name: 'AT+BLEADVSTOP', desc: '结束 BLE 广播' },
        { name: 'AT+BLECONN', desc: '建立 BLE 连接' },
        { name: 'AT+BLECONNPARAM', desc: '更新 BLE 连接参数' },
        { name: 'AT+BLEDISCONN', desc: '断开 BLE 连接' },
        { name: 'AT+BLEDATALEN', desc: '设置 BLE 数据包长度' },
        { name: 'AT+BLECFGMTU', desc: '设置 GATT MTU 的长度' },
        { name: 'AT+BLEGATTSSRVCRE', desc: 'GATTS 创建服务' },
        { name: 'AT+BLEGATTSSRVSTART', desc: 'GATTS 开启服务' },
        { name: 'AT+BLEGATTSSRVSTOP', desc: 'GATTS 停止服务' },
        { name: 'AT+BLEGATTSSRV', desc: 'GATTS 发现服务' },
        { name: 'AT+BLEGATTSCHAR', desc: 'GATTS 发现服务特征' },
        { name: 'AT+BLEGATTSNTFY', desc: 'GATTS 通知服务特征值' },
        { name: 'AT+BLEGATTSIND', desc: 'GATTS 指示服务特征值' },
        { name: 'AT+BLEGATTSSETATTR', desc: 'GATTS 设置服务特征值' },
        { name: 'AT+BLEGATTCPRIMSRV', desc: 'GATTC 发现基本服务' },
        { name: 'AT+BLEGATTCINCLSRV', desc: 'GATTC 发现包含服务' },
        { name: 'AT+BLEGATTCCHAR', desc: 'GATTC 发现服务特征' },
        { name: 'AT+BLEGATTCRD', desc: 'GATTC 读取服务特征值' },
        { name: 'AT+BLEGATTCWR', desc: 'GATTC 写服务特征值' },
        { name: 'AT+BLESPPCFG', desc: '配置 BLE 透传模式' },
        { name: 'AT+BLESPP', desc: '开启 BLE 透传模式' },
        { name: 'AT+BLESECPARAM', desc: '设置 BLE 加密参数' },
        { name: 'AT+BLEENC', desc: '发起 BLE 加密请求' },
        { name: 'AT+BLEENCRSP', desc: '回复 BLE 加密请求' },
        { name: 'AT+BLEKEYREPLY', desc: '回复 BLE 加密密钥' },
        { name: 'AT+BLECONFREPLY', desc: '回复 BLE 配对结果' },
        { name: 'AT+BLEENCDEV', desc: '查询已绑定的设备' },
        { name: 'AT+BLEENCCLEAR', desc: '解除绑定' }
    ]
};
