window.picolibcTreeData = [
  {
    name: "picolibc-main-微库newlib-nano",
    type: "folder",
    children: [
      { name: "CMakeLists.txt", desc: "CMake 构建配置文件", type: "file" },
      { name: "CODE_OF_CONDUCT.md", desc: "行为准则文档", type: "file" },
      { name: "CONTRIBUTING.md", desc: "贡献指南文档", type: "file" },
      { name: "COPYING.GPL2", desc: "GPL2 许可证文件", type: "file" },
      { name: "COPYING.NEWLIB", desc: "Newlib 许可证文件", type: "file" },
      { name: "COPYING.picolibc", desc: "Picolibc 许可证文件", type: "file" },
      { name: "README.md", desc: "项目说明文档", type: "file" },
      {
        name: "cmake",
        type: "folder",
        children: [
          { name: "TC-arm-none-eabi.ld", desc: "ARM 无系统链接脚本", type: "file" },
          { name: "TC-clang-thumbv6m.cmake", desc: "Clang Thumbv6m 工具链", type: "file" },
          { name: "TC-clang-thumbv7m.cmake", desc: "Clang Thumbv7m 工具链", type: "file" },
          { name: "TC-microbit.ld", desc: "Microbit 链接脚本", type: "file" },
          { name: "TC-rx.cmake", desc: "RX 架构工具链", type: "file" },
          { name: "TC-rx.ld", desc: "RX 架构链接脚本", type: "file" },
          { name: "TC-thumbv6m.cmake", desc: "Thumbv6m工具链", type: "file" },
          { name: "TC-thumbv7m.cmake", desc: "Thumbv7m工具链", type: "file" },
          { name: "have-bitfields-in-packed-structs.c", desc: "位字段检测代码", type: "file" },
          { name: "have-cc-inhibit-loop-to-libcall.c", desc: "循环优化检测代码", type: "file" },
          { name: "have-complex.c", desc: "复数支持检测代码", type: "file" },
          { name: "picolibc.cmake", desc: "Picolibc CMake 模块", type: "file" },
          { name: "simple-main.c", desc: "简单主程序示例", type: "file" }
        ]
      },
      { name: "cross.tmpl", desc: "交叉编译模板", type: "file" },
      {
        name: "doc",
        type: "folder",
        children: [
          { name: "build.md", desc: "构建说明文档", type: "file" },
          { name: "ctype.md", desc: "字符类型文档", type: "file" },
          { name: "embedsource.md", desc: "嵌入源码文档", type: "file" },
          { name: "init.md", desc: "初始化文档", type: "file" },
          { name: "linking.md", desc: "链接说明文档", type: "file" },
          { name: "locking.md", desc: "锁机制文档", type: "file" },
          { name: "os.md", desc: "操作系统接口文档", type: "file" },
          { name: "picolibc.svg", desc: "项目矢量图标", type: "file" },
          { name: "printf-sample", desc: "printf 示例目录", type: "file" },
          { name: "printf.md", desc: "printf 格式说明文档", type: "file" },
          { name: "releasing.md", desc: "发布说明文档", type: "file" },
          { name: "testing.md", desc: "测试说明文档", type: "file" },
          { name: "tls.md", desc: "线程本地存储文档", type: "file" },
          { name: "using.md", desc: "使用指南文档", type: "file" }
        ]
      },
      { name: "find-copyright", desc: "版权查找脚本", type: "file" },
      {
        name: "hello-world",
        type: "folder",
        children: [
          { name: "Makefile", desc: "构建配置文件", type: "file" },
          { name: "README.md", desc: "示例说明文档", type: "file" },
          { name: "aarch64-cpp.ld", desc: "AArch64 C++链接脚本", type: "file" },
          { name: "aarch64.ld", desc: "AArch64 链接脚本", type: "file" },
          { name: "arm-cpp.ld", desc: "ARM C++链接脚本", type: "file" },
          { name: "arm.ld", desc: "ARM 链接脚本", type: "file" },
          { name: "hello-world.c", desc: "C 示例程序", type: "file" },
          { name: "hello-worldpp.cpp", desc: "C++示例程序", type: "file" },
          { name: "printf.c", desc: "printf 测试程序", type: "file" },
          { name: "riscv-cpp.ld", desc: "RISC-V C++链接脚本", type: "file" },
          { name: "riscv.ld", desc: "RISC-V 链接脚本", type: "file" },
          { name: "run-aarch64", desc: "AArch64 运行脚本", type: "file" },
          { name: "run-aarch64++", desc: "AArch64 C++运行脚本", type: "file" },
          { name: "run-arm", desc: "ARM 运行脚本", type: "file" },
          { name: "run-riscv", desc: "RISC-V 运行脚本", type: "file" },
          { name: "run-riscv++", desc: "RISC-V C++运行脚本", type: "file" },
          { name: "test-file", desc: "测试文件", type: "file" }
        ]
      },
      { name: "make-copyrights", desc: "版权生成脚本", type: "file" },
      { name: "meson.build", desc: "Meson 构建配置", type: "file" },
      { name: "meson_options.txt", desc: "Meson 构建选项", type: "file" },
      {
        name: "newlib",
        type: "folder",
        children: [
          { name: "CMakeLists.txt", desc: "CMake 配置文件", type: "file" },
          { name: "ChangeLog", desc: "变更日志", type: "file" },
          { name: "ChangeLog-2015", desc: "2015 年变更日志", type: "file" },
          { name: "HOWTO", desc: "使用指南", type: "file" },
          { name: "MAINTAINERS", desc: "维护者列表", type: "file" },
          { name: "NEWS", desc: "新闻动态", type: "file" },
          { name: "README", desc: "说明文档", type: "file" },
          { name: "doc", desc: "文档目录", type: "file" },
          { name: "empty.c", desc: "空实现文件", type: "file" },
          { name: "libc", desc: "C 标准库实现", type: "file" },
          { name: "libm", desc: "数学库实现", type: "file" },
          { name: "man.xsl", desc: "文档样式表", type: "file" },
          { name: "meson.build", desc: "Meson 构建配置", type: "file" },
          { name: "refcontainers.xslt", desc: "容器转换样式", type: "file" },
          { name: "testsuite", desc: "测试套件", type: "file" }
        ]
      },
      {
        name: "picocrt",
        type: "folder",
        children: [
          { name: "CMakeLists.txt", desc: "CMake 配置文件", type: "file" },
          { name: "crt0-none.c", desc: "无系统启动文件", type: "file" },
          { name: "crt0.h", desc: "启动文件头", type: "file" },
          { name: "machine", desc: "机器相关代码", type: "file" },
          { name: "meson.build", desc: "Meson 构建配置", type: "file" },
          { name: "shared", desc: "共享组件", type: "file" }
        ]
      },
      { name: "picolibc.h.in", desc: "Picolibc 配置模板", type: "file" },
      { name: "picolibc.ld.in", desc: "链接脚本模板", type: "file" },
      { name: "picolibc.specs.in", desc: "GCC 规格模板", type: "file" },
      {
        name: "scripts",
        type: "folder",
        children: [
          { name: "GeneratePicolibcCrossFile.sh", desc: "交叉编译文件生成脚本", type: "file" },
          { name: "cross-*.txt", desc: "各架构交叉编译配置（多个）", type: "file" },
          { name: "do-*-configure", desc: "各平台配置脚本（多个）", type: "file" },
          { name: "duplicate-names", desc: "重复名称检查", type: "file" },
          { name: "monitor-e9", desc: "调试监控工具", type: "file" },
          { name: "run-*", desc: "各平台运行脚本 （多个）", type: "file" },
          { name: "test-picolibc", desc: "测试脚本", type: "file" },
          { name: "validate-cdefs", desc: "定义验证工具", type: "file" }
        ]
      },
      {
        name: "semihost",
        type: "folder",
        children: [
          { name: "CMakeLists.txt", desc: "CMake 配置文件", type: "file" },
          { name: "*.c", desc: "半主机系统调用实现（多个）", type: "file" },
          { name: "fake", desc: "伪实现目录", type: "file" },
          { name: "machine", desc: "机器相关代码", type: "file" },
          { name: "meson.build", desc: "Meson 构建配置", type: "file" },
          { name: "semihost-private.h", desc: "私有头文件", type: "file" },
          { name: "semihost.h", desc: "半主机接口头", type: "file" },
          { name: "sys_*.c", desc: "系统调用实现 （多个）", type: "file" }
        ]
      },
      {
        name: "test",
        type: "folder",
        children: [
          { name: "CMakeLists.txt", desc: "CMake 配置文件", type: "file" },
          { name: "CP720", desc: "代码页720 测试", type: "file" },
          { name: "*.c", desc: "各种测试用例（多个）", type: "file" },
          { name: "*.cpp", desc: "C++ 测试用例", type: "file" },
          { name: "*.h", desc: "测试头文件", type: "file" },
          { name: "libc-testsuite", desc: "C 库测试套件", type: "file" },
          { name: "semihost", desc: "半主机测试", type: "file" },
          { name: "meson.build", desc: "Meson 构建配置", type: "file" }
        ]
      },
      {
        name: "zephyr",
        type: "folder",
        children: [
          { name: "Kconfig", desc: "内核配置文件", type: "file" },
          { name: "module.yml", desc: "模块配置文件", type: "file" },
          { name: "zephyr.cmake", desc: "Zephyr CMake 模块", type: "file" }
        ]
      }
    ]
  }
];

window.newlibTreeData = [
  {
    name: "argz (17)",
    type: "folder",
    children: [
      { name: "CMakeLists.txt", desc: "CMake 构建配置文件", type: "file" },
      { name: "argz_add.c", desc: "添加字符串到argz", type: "file" },
      { name: "argz_add_sep.c", desc: "添加分隔符字符串", type: "file" },
      { name: "argz_append.c", desc: "追加argz", type: "file" },
      { name: "argz_count.c", desc: "计数argz 条目", type: "file" },
      { name: "argz_create.c", desc: "创建argz", type: "file" },
      { name: "argz_create_sep.c", desc: "创建带分隔符argz", type: "file" },
      { name: "argz_delete.c", desc: "删除argz 条目", type: "file" },
      { name: "argz_extract.c", desc: "提取argz", type: "file" },
      { name: "argz_insert.c", desc: "插入argz", type: "file" },
      { name: "argz_next.c", desc: "获取下一个argz", type: "file" },
      { name: "argz_replace.c", desc: "替换argz", type: "file" },
      { name: "argz_stringify.c", desc: "转换为字符串", type: "file" },
      { name: "buf_findstr.c", desc: "缓冲区查找字符串", type: "file" },
      { name: "buf_findstr.h", desc: "缓冲区查找头文件", type: "file" },
      { name: "envz_add.c", desc: "添加环境变量", type: "file" },
      { name: "envz_entry.c", desc: "获取环境条目", type: "file" }
    ]
  },
  {
    name: "ctype (64)",
    type: "folder",
    children: [
      { name: "CMakeLists.txt", desc: "CMake 构建配置文件", type: "file" },
      { name: "caseconv.c", desc: "大小写转换", type: "file" },
      { name: "caseconv.t", desc: "大小写转换测试", type: "file" },
      { name: "categories.h", desc: "字符分类头文件", type: "file" },
      { name: "ctype.tex", desc: "字符类型文档", type: "file" },
      { name: "ctype_.c", desc: "字符类型实现", type: "file" },
      { name: "ctype_.h", desc: "字符类型头文件", type: "file" },
      { name: "ctype_extended.h", desc: "扩展字符类型", type: "file" },
      { name: "ctype_table.c", desc: "字符类型表", type: "file" },
      { name: "ctype_table.h", desc: "字符类型表头文件", type: "file" },
      { name: "ctype_wide.c", desc: "宽字符类型", type: "file" },
      { name: "isalnum.c", desc: "是否字母数字", type: "file" },
      { name: "isalnum_l.c", desc: "本地化字母数字检查", type: "file" },
      { name: "isalpha.c", desc: "是否字母", type: "file" },
      { name: "isalpha_l.c", desc: "本地化字母检查", type: "file" },
      { name: "isascii.c", desc: "是否ASCII 字符", type: "file" },
      { name: "isascii_l.c", desc: "本地化ASCII 检查", type: "file" },
      { name: "isblank.c", desc: "是否空白字符", type: "file" },
      { name: "isblank_l.c", desc: "本地化空白检查", type: "file" },
      { name: "iscntrl.c", desc: "是否控制字符", type: "file" },
      { name: "iscntrl_l.c", desc: "本地化控制字符检查", type: "file" },
      { name: "isdigit.c", desc: "是否数字", type: "file" },
      { name: "isdigit_l.c", desc: "本地化数字检查", type: "file" },
      { name: "isgraph.c", desc: "是否图形字符", type: "file" },
      { name: "isgraph_l.c", desc: "本地化图形字符检查", type: "file" },
      { name: "islower.c", desc: "是否小写字母", type: "file" },
      { name: "islower_l.c", desc: "本地化小写检查", type: "file" },
      { name: "isprint.c", desc: "是否可打印字符", type: "file" },
      { name: "isprint_l.c", desc: "本地化可打印检查", type: "file" },
      { name: "ispunct.c", desc: "是否标点符号", type: "file" },
      { name: "ispunct_l.c", desc: "本地化标点检查", type: "file" },
      { name: "isspace.c", desc: "是否空白字符", type: "file" },
      { name: "isspace_l.c", desc: "本地化空白检查", type: "file" },
      { name: "isupper.c", desc: "是否大写字母", type: "file" },
      { name: "isupper_l.c", desc: "本地化大写检查", type: "file" },
      { name: "iswalnum.c", desc: "宽字符字母数字检查", type: "file" },
      { name: "iswalnum_l.c", desc: "本地化宽字符字母数字", type: "file" },
      { name: "iswalpha.c", desc: "宽字符字母检查", type: "file" },
      { name: "iswalpha_l.c", desc: "本地化宽字符字母", type: "file" },
      { name: "iswblank.c", desc: "宽字符空白检查", type: "file" },
      { name: "iswblank_l.c", desc: "本地化宽字符空白", type: "file" },
      { name: "iswcntrl.c", desc: "宽字符控制检查", type: "file" },
      { name: "iswcntrl_l.c", desc: "本地化宽字符控制", type: "file" },
      { name: "iswctype.c", desc: "宽字符类型检查", type: "file" },
      { name: "iswctype_l.c", desc: "本地化宽字符类型", type: "file" },
      { name: "iswdigit.c", desc: "宽字符数字检查", type: "file" },
      { name: "iswdigit_l.c", desc: "本地化宽字符数字", type: "file" },
      { name: "iswgraph.c", desc: "宽字符图形检查", type: "file" },
      { name: "iswgraph_l.c", desc: "本地化宽字符图形", type: "file" },
      { name: "iswlower.c", desc: "宽字符小写检查", type: "file" },
      { name: "iswlower_l.c", desc: "本地化宽字符小写", type: "file" },
      { name: "iswprint.c", desc: "宽字符可打印检查", type: "file" },
      { name: "iswprint_l.c", desc: "本地化宽字符可打印", type: "file" },
      { name: "iswpunct.c", desc: "宽字符标点检查", type: "file" },
      { name: "iswpunct_l.c", desc: "本地化宽字符标点", type: "file" },
      { name: "iswspace.c", desc: "宽字符空白检查", type: "file" },
      { name: "iswspace_l.c", desc: "本地化宽字符空白", type: "file" },
      { name: "iswupper.c", desc: "宽字符大写检查", type: "file" },
      { name: "iswupper_l.c", desc: "本地化宽字符大写", type: "file" },
      { name: "iswxdigit.c", desc: "宽字符十六进制检查", type: "file" },
      { name: "iswxdigit_l.c", desc: "本地化宽字符十六进制", type: "file" },
      { name: "isxdigit.c", desc: "是否十六进制数字", type: "file" },
      { name: "isxdigit_l.c", desc: "本地化十六进制检查", type: "file" },
      { name: "jp2uc.c", desc: "JIS 到Unicode 转换", type: "file" },
      { name: "jp2uc.h", desc: "JIS 到Unicode 转换头文件", type: "file" },
      { name: "local.h", desc: "本地化头文件", type: "file" },
      { name: "meson.build", desc: "Meson 构建配置", type: "file" },
      { name: "mkcaseconv", desc: "大小写转换生成器", type: "file" },
      { name: "mkcategories", desc: "分类生成器", type: "file" },
      { name: "mkctype-extended.py", desc: "扩展字符类型生成", type: "file" },
      { name: "mkctype.py", desc: "字符类型生成器", type: "file" },
      { name: "mkunidata", desc: "Unicode 数据生成器", type: "file" },
      { name: "toascii.c", desc: "转换为ASCII", type: "file" },
      { name: "toascii_l.c", desc: "本地化ASCII 转换", type: "file" },
      { name: "tolower.c", desc: "转换为小写", type: "file" },
      { name: "tolower_l.c", desc: "本地化小写转换", type: "file" },
      { name: "toupper.c", desc: "转换为大写", type: "file" },
      { name: "toupper_l.c", desc: "本地化大写转换", type: "file" },
      { name: "towctrans.c", desc: "宽字符转换", type: "file" },
      { name: "towctrans_l.c", desc: "本地化宽字符转换", type: "file" },
      { name: "towlower.c", desc: "宽字符转小写", type: "file" },
      { name: "towlower_l.c", desc: "本地化宽字符小写", type: "file" },
      { name: "towupper.c", desc: "宽字符转大写", type: "file" },
      { name: "towupper_l.c", desc: "本地化宽字符大写", type: "file" },
      { name: "wctrans.c", desc: "宽字符转换映射", type: "file" },
      { name: "wctrans_l.c", desc: "本地化宽字符映射", type: "file" },
      { name: "wctype.c", desc: "宽字符类型", type: "file" },
      { name: "wctype_l.c", desc: "本地化宽字符类型", type: "file" }
    ]
  },
  {
    name: "errno (3)",
    type: "folder",
    children: [
      { name: "CMakeLists.txt", desc: "CMake 构建配置文件", type: "file" },
      { name: "errno.c", desc: "错误号定义", type: "file" },
      { name: "meson.build", desc: "Meson 构建配置", type: "file" }
    ]
  },
  {
    name: "iconv (5)",
    type: "folder",
    children: [
      { name: "CMakeLists.txt", desc: "CMake 构建配置文件", type: "file" },
      { name: "iconv.c", desc: "字符编码转换", type: "file" },
      { name: "iconv_close.c", desc: "关闭iconv 转换", type: "file" },
      { name: "iconv_open.c", desc: "打开iconv 转换", type: "file" },
      { name: "iconv_private.h", desc: "iconv 私有头文件", type: "file" },
      { name: "meson.build", desc: "Meson 构建配置", type: "file" }
    ]
  },
  {
    name: "include (68)",
    type: "folder",
    children: [
      { name: "CMakeLists.txt", desc: "CMake 构建配置文件", type: "file" },
      { name: "_newlib_version.h", desc: "Newlib 版本头文件", type: "file" },
      { name: "_syslist.h", desc: "系统列表头文件", type: "file" },
      { name: "alloca.h", desc: "内存分配头文件", type: "file" },
      { name: "ar.h", desc: "归档头文件", type: "file" },
      { name: "argz.h", desc: "argz 函数头文件", type: "file" },
      { name: "arpa", desc: "网络相关头文件目录", type: "file" },
      { name: "assert.h", desc: "断言头文件", type: "file" },
      { name: "bits", desc: "底层定义目录", type: "file" },
      { name: "byteswap.h", desc: "字节交换头文件", type: "file" },
      { name: "complex.h", desc: "复数运算头文件", type: "file" },
      { name: "cpio.h", desc: "cpio 归档头文件", type: "file" },
      { name: "ctype.h", desc: "字符类型头文件", type: "file" },
      { name: "devctl.h", desc: "设备控制头文件", type: "file" },
      { name: "dirent.h", desc: "目录条目头文件", type: "file" },
      { name: "endian.h", desc: "字节序头文件", type: "file" },
      { name: "envlock.h", desc: "环境锁头文件", type: "file" },
      { name: "envz.h", desc: "环境变量头文件", type: "file" },
      { name: "errno.h", desc: "错误号头文件", type: "file" },
      { name: "fastmath.h", desc: "快速数学头文件", type: "file" },
      { name: "fcntl.h", desc: "文件控制头文件", type: "file" },
      { name: "fenv.h", desc: "浮点环境头文件", type: "file" },
      { name: "fnmatch.h", desc: "文件名匹配头文件", type: "file" },
      { name: "ftw.h", desc: "文件树遍历头文件", type: "file" },
      { name: "getopt.h", desc: "命令行选项头文件", type: "file" },
      { name: "glob.h", desc: "文件名匹配头文件", type: "file" },
      { name: "grp.h", desc: "用户组头文件", type: "file" },
      { name: "iconv.h", desc: "字符编码转换头文件", type: "file" },
      { name: "ieeefp.h", desc: "IEEE 浮点头文件", type: "file" },
      { name: "inttypes.h", desc: "整数类型头文件", type: "file" },
      { name: "langinfo.h", desc: "语言信息头文件", type: "file" },
      { name: "libgen.h", desc: "库生成头文件", type: "file" },
      { name: "limits.h", desc: "数值限制头文件", type: "file" },
      { name: "locale.h", desc: "本地化头文件", type: "file" },
      { name: "machine", desc: "机器相关头文件目录", type: "file" },
      { name: "malloc.h", desc: "内存分配头文件", type: "file" },
      { name: "math.h", desc: "数学函数头文件", type: "file" },
      { name: "memory.h", desc: "内存操作头文件", type: "file" },
      { name: "meson.build", desc: "Meson 构建配置", type: "file" },
      { name: "ndbm.h", desc: "数据库管理头文件", type: "file" },
      { name: "newlib.h", desc: "Newlib 头文件", type: "file" },
      { name: "paths.h", desc: "路径定义头文件", type: "file" },
      { name: "picotls.h", desc: "Picolibc TLS 头文件", type: "file" },
      { name: "pwd.h", desc: "用户密码头文件", type: "file" },
      { name: "regdef.h", desc: "寄存器定义头文件", type: "file" },
      { name: "regex.h", desc: "正则表达式头文件", type: "file" },
      { name: "rpc", desc: "远程过程调用目录", type: "file" },
      { name: "sched.h", desc: "调度头文件", type: "file" },
      { name: "search.h", desc: "搜索算法头文件", type: "file" },
      { name: "setjmp.h", desc: "非局部跳转头文件", type: "file" },
      { name: "signal.h", desc: "信号处理头文件", type: "file" },
      { name: "spawn.h", desc: "进程生成头文件", type: "file" },
      { name: "ssp", desc: "栈保护目录", type: "file" },
      { name: "stdint.h", desc: "标准整数类型头文件", type: "file" },
      { name: "stdlib.h", desc: "标准库头文件", type: "file" },
      { name: "stdnoreturn.h", desc: "无返回函数头文件", type: "file" },
      { name: "string.h", desc: "字符串操作头文件", type: "file" },
      { name: "strings.h", desc: "字符串操作头文件", type: "file" },
      { name: "sys", desc: "系统调用目录", type: "file" },
      { name: "tar.h", desc: "tar 归档头文件", type: "file" },
      { name: "termios.h", desc: "终端I/O 头文件", type: "file" },
      { name: "time.h", desc: "时间函数头文件", type: "file" },
      { name: "uchar.h", desc: "Unicode字符头文件", type: "file" },
      { name: "unctrl.h", desc: "控制字符头文件", type: "file" },
      { name: "unistd.h", desc: "标准符号常量头文件", type: "file" },
      { name: "utime.h", desc: "文件时间头文件", type: "file" },
      { name: "utmp.h", desc: "用户登录记录头文件", type: "file" },
      { name: "wchar.h", desc: "宽字符头文件", type: "file" },
      { name: "wctype.h", desc: "宽字符类型头文件", type: "file" },
      { name: "wordexp.h", desc: "单词扩展头文件", type: "file" }
    ]
  },
  {
    name: "libc.in.xml (1)",
    type: "folder",
    children: [
      { name: "libc.in.xml", desc: "Libc XML 配置文件", type: "file" }
    ]
  },
  {
    name: "locale (14)",
    type: "folder",
    children: [
      { name: "CMakeLists.txt", desc: "CMake 构建配置文件", type: "file" },
      { name: "duplocale.c", desc: "复制本地化对象", type: "file" },
      { name: "freelocale.c", desc: "释放本地化对象", type: "file" },
      { name: "getlocalename_l.c", desc: "获取本地化名称", type: "file" },
      { name: "locale_ctype_ptr.c", desc: "本地化字符类型指针", type: "file" },
      { name: "locale_ctype_ptr_l.c", desc: "本地化字符类型指针", type: "file" },
      { name: "locale_mb_cur_max.c", desc: "本地化多字节最大长度", type: "file" },
      { name: "locale_names.c", desc: "本地化名称", type: "file" },
      { name: "locale_private.h", desc: "本地化私有头文件", type: "file" },
      { name: "localeconv.c", desc: "本地化数字格式", type: "file" },
      { name: "localedata.c", desc: "本地化数据", type: "file" },
      { name: "meson.build", desc: "Meson 构建配置", type: "file" },
      { name: "newlocale.c", desc: "创建本地化对象", type: "file" },
      { name: "nl_langinfo.c", desc: "获取语言信息", type: "file" },
      { name: "posix_locale.c", desc: "POSIX 本地化", type: "file" },
      { name: "setlocale.c", desc: "设置本地化", type: "file" },
      { name: "timedata.c", desc: "时间数据", type: "file" },
      { name: "uselocale.c", desc: "使用本地化对象", type: "file" }
    ]
  },
  {
    name: "machine (61)",
    type: "folder",
    children: [
      { name: "CMakeLists.txt", desc: "CMake 构建配置文件", type: "file" },
      { name: "aarch64", desc: "AArch64 架构支持", type: "file" },
      { name: "amdgcn", desc: "AMD GCN 架构支持", type: "file" },
      { name: "arc", desc: "ARC 架构支持", type: "file" },
      { name: "arc64", desc: "ARC 64 位架构支持", type: "file" },
      { name: "arm", desc: "ARM 架构支持", type: "file" },
      { name: "avr", desc: "AVR 架构支持", type: "file" },
      { name: "bfin", desc: "Blackfin 架构支持", type: "file" },
      { name: "cr16", desc: "CR16 架构支持", type: "file" },
      { name: "cris", desc: "CRIS 架构支持", type: "file" },
      { name: "crx", desc: "CRX 架构支持", type: "file" },
      { name: "csky", desc: "C-SKY 架构支持", type: "file" },
      { name: "d10v", desc: "D10V 架构支持", type: "file" },
      { name: "d30v", desc: "D30V 架构支持", type: "file" },
      { name: "epiphany", desc: "Epiphany 架构支持", type: "file" },
      { name: "fr30", desc: "FR30 架构支持", type: "file" },
      { name: "frv", desc: "FRV 架构支持", type: "file" },
      { name: "ft32", desc: "FT32 架构支持", type: "file" },
      { name: "h8300", desc: "H8/300 架构支持", type: "file" },
      { name: "h8500", desc: "H8/500 架构支持", type: "file" },
      { name: "hppa", desc: "HP PA 架构支持", type: "file" },
      { name: "i960", desc: "i960 架构支持", type: "file" },
      { name: "iq2000", desc: "IQ2000 架构支持", type: "file" },
      { name: "lm32", desc: "LM32 架构支持", type: "file" },
      { name: "loongarch", desc: "LoongArch 架构支持", type: "file" },
      { name: "m32c", desc: "M32C 架构支持", type: "file" },
      { name: "m32r", desc: "M32R 架构支持", type: "file" },
      { name: "m68hc11", desc: "68HC11 架构支持", type: "file" },
      { name: "m68k", desc: "68K 架构支持", type: "file" },
      { name: "m88k", desc: "88K 架构支持", type: "file" },
      { name: "mep", desc: "MEP 架构支持", type: "file" },
      { name: "microblaze", desc: "MicroBlaze 架构支持", type: "file" },
      { name: "mips", desc: "MIPS 架构支持", type: "file" },
      { name: "mn10200", desc: "MN10200 架构支持", type: "file" },
      { name: "mn10300", desc: "MN10300 架构支持", type: "file" },
      { name: "moxie", desc: "Moxie 架构支持", type: "file" },
      { name: "msp430", desc: "MSP430 架构支持", type: "file" },
      { name: "mt", desc: "MT 架构支持", type: "file" },
      { name: "nds32", desc: "NDS32 架构支持", type: "file" },
      { name: "necv70", desc: "NEC V70 架构支持", type: "file" },
      { name: "nios2", desc: "Nios II 架构支持", type: "file" },
      { name: "nvptx", desc: "NVPTX 架构支持", type: "file" },
      { name: "or1k", desc: "OpenRISC 架构支持", type: "file" },
      { name: "powerpc", desc: "PowerPC 架构支持", type: "file" },
      { name: "pru", desc: "PRU 架构支持", type: "file" },
      { name: "riscv", desc: "RISC-V 架构支持", type: "file" },
      { name: "rl78", desc: "RL78 架构支持", type: "file" },
      { name: "rx", desc: "RX 架构支持", type: "file" },
      { name: "sh", desc: "SuperH 架构支持", type: "file" },
      { name: "sparc", desc: "SPARC 架构支持", type: "file" },
      { name: "spu", desc: "SPU 架构支持", type: "file" },
      { name: "tic4x", desc: "TMS320C4x 架构支持", type: "file" },
      { name: "tic6x", desc: "TMS320C6x 架构支持", type: "file" },
      { name: "tic80", desc: "TIC80 架构支持", type: "file" },
      { name: "v850", desc: "V850 架构支持", type: "file" },
      { name: "visium", desc: "Visium 架构支持", type: "file" },
      { name: "w65", desc: "W65 架构支持", type: "file" },
      { name: "x86", desc: "x86 架构支持", type: "file" },
      { name: "x86_64", desc: "x86_64 架构支持", type: "file" },
      { name: "xc16x", desc: "XC16x 架构支持", type: "file" },
      { name: "xstormy16", desc: "XStormy16 架构支持", type: "file" },
      { name: "xtensa", desc: "Xtensa 架构支持", type: "file" },
      { name: "z8k", desc: "Z8000 架构支持", type: "file" }
    ]
  },
  {
    name: "misc (6)",
    type: "folder",
    children: [
      { name: "CMakeLists.txt", desc: "CMake 构建配置文件", type: "file" },
      { name: "ffs.c", desc: "查找第一个设置位", type: "file" },
      { name: "fini.c", desc: "终止函数", type: "file" },
      { name: "init.c", desc: "初始化函数", type: "file" },
      { name: "lock.c", desc: "锁实现", type: "file" },
      { name: "meson.build", desc: "Meson 构建配置", type: "file" },
      { name: "misc.tex", desc: "杂项文档", type: "file" },
      { name: "unctrl.c", desc: "控制字符转换", type: "file" }
    ]
  },
  {
    name: "picolib (6)",
    type: "folder",
    children: [
      { name: "CMakeLists.txt", desc: "CMake 构建配置文件", type: "file" },
      { name: "dso_handle.c", desc: "DSO 句柄", type: "file" },
      { name: "getauxval.c", desc: "获取辅助值", type: "file" },
      { name: "inittls.c", desc: "初始化线程本地存储", type: "file" },
      { name: "machine", desc: "机器相关代码", type: "file" },
      { name: "meson.build", desc: "Meson 构建配置", type: "file" },
      { name: "picosbrk.c", desc: "Picolibc 堆管理", type: "file" }
    ]
  },
  {
    name: "posix (11)",
    type: "folder",
    children: [
      { name: "CMakeLists.txt", desc: "CMake 构建配置文件", type: "file" },
      { name: "basename.c", desc: "获取路径基名", type: "file" },
      { name: "cclass.h", desc: "字符类头文件", type: "file" },
      { name: "cname.h", desc: "字符名称头文件", type: "file" },
      { name: "collate.h", desc: "排序规则头文件", type: "file" },
      { name: "collcmp.c", desc: "字符串比较", type: "file" },
      { name: "dirname.c", desc: "获取目录名", type: "file" },
      { name: "engine.c", desc: "正则表达式引擎", type: "file" },
      { name: "fnmatch.c", desc: "文件名匹配", type: "file" },
      { name: "fpathconf.c", desc: "路径配置", type: "file" },
      { name: "meson.build", desc: "Meson 构建配置", type: "file" },
      { name: "pathconf.c", desc: "路径配置", type: "file" },
      { name: "regcomp.c", desc: "正则表达式编译", type: "file" },
      { name: "regerror.c", desc: "正则表达式错误", type: "file" },
      { name: "regex2.h", desc: "正则表达式头文件", type: "file" },
      { name: "regexec.c", desc: "正则表达式执行", type: "file" },
      { name: "regfree.c", desc: "释放正则表达式", type: "file" },
      { name: "rune.h", desc: "字符编码头文件", type: "file" },
      { name: "runetype.h", desc: "字符类型头文件", type: "file" },
      { name: "sysexits.h", desc: "退出状态码", type: "file" },
      { name: "utils.h", desc: "实用工具头文件", type: "file" }
    ]
  },
  {
    name: "search (16)",
    type: "folder",
    children: [
      { name: "CMakeLists.txt", desc: "CMake 构建配置文件", type: "file" },
      { name: "bsd_qsort_r.c", desc: "BSD qsort_r 实现", type: "file" },
      { name: "bsearch.c", desc: "二分查找", type: "file" },
      { name: "db_local.h", desc: "本地数据库头文件", type: "file" },
      { name: "extern.h", desc: "外部声明头文件", type: "file" },
      { name: "hash.c", desc: "哈希表实现", type: "file" },
      { name: "hash.h", desc: "哈希表头文件", type: "file" },
      { name: "hash_bigkey.c", desc: "大键哈希处理", type: "file" },
      { name: "hash_buf.c", desc: "缓冲区哈希", type: "file" },
      { name: "hash_func.c", desc: "哈希函数", type: "file" },
      { name: "hash_log2.c", desc: "哈希对数计算", type: "file" },
      { name: "hash_page.c", desc: "哈希分页", type: "file" },
      { name: "hcreate.3", desc: "哈希表创建手册", type: "file" },
      { name: "hcreate.c", desc: "创建哈希表", type: "file" },
      { name: "hcreate_r.c", desc: "可重入哈希表创建", type: "file" },
      { name: "meson.build", desc: "Meson 构建配置", type: "file" },
      { name: "ndbm.c", desc: "NDBM 数据库实现", type: "file" },
      { name: "page.h", desc: "分页头文件", type: "file" },
      { name: "qsort.c", desc: "快速排序", type: "file" },
      { name: "qsort_r.c", desc: "可重入快速排序", type: "file" },
      { name: "tdelete.c", desc: "删除树节点", type: "file" },
      { name: "tdestroy.c", desc: "销毁树", type: "file" },
      { name: "tfind.c", desc: "查找树节点", type: "file" },
      { name: "tsearch.3", desc: "树搜索手册", type: "file" },
      { name: "tsearch.c", desc: "树搜索实现", type: "file" },
      { name: "twalk.c", desc: "遍历树", type: "file" }
    ]
  },
  {
    name: "signal (5)",
    type: "folder",
    children: [
      { name: "CMakeLists.txt", desc: "CMake 构建配置文件", type: "file" },
      { name: "meson.build", desc: "Meson 构建配置", type: "file" },
      { name: "psignal.c", desc: "打印信号信息", type: "file" },
      { name: "sig2str.c", desc: "信号转字符串", type: "file" },
      { name: "signal.c", desc: "信号处理", type: "file" },
      { name: "signal.tex", desc: "信号文档", type: "file" }
    ]
  },
  {
    name: "ssp (15)",
    type: "folder",
    children: [
      { name: "CMakeLists.txt", desc: "CMake 构建配置文件", type: "file" },
      { name: "chk_fail.c", desc: "检查失败处理", type: "file" },
      { name: "gets_chk.c", desc: "安全gets 实现", type: "file" },
      { name: "memcpy_chk.c", desc: "安全内存复制", type: "file" },
      { name: "memmove_chk.c", desc: "安全内存移动", type: "file" },
      { name: "mempcpy_chk.c", desc: "安全内存复制并返回指针", type: "file" },
      { name: "memset_chk.c", desc: "安全内存设置", type: "file" },
      { name: "meson.build", desc: "Meson 构建配置", type: "file" },
      { name: "snprintf_chk.c", desc: "安全格式化输出", type: "file" },
      { name: "sprintf_chk.c", desc: "安全格式化输出", type: "file" },
      { name: "ssp.tex", desc: "栈保护文档", type: "file" },
      { name: "stack_protector.c", desc: "栈保护实现", type: "file" },
      { name: "stpcpy_chk.c", desc: "安全字符串复制", type: "file" },
      { name: "stpncpy_chk.c", desc: "安全字符串复制并返回指针", type: "file" },
      { name: "strcat_chk.c", desc: "安全字符串连接", type: "file" },
      { name: "strcpy_chk.c", desc: "安全字符串复制", type: "file" },
      { name: "strncat_chk.c", desc: "安全字符串连接", type: "file" },
      { name: "strncpy_chk.c", desc: "安全字符串复制", type: "file" },
      { name: "vsnprintf_chk.c", desc: "安全可变参数格式化输出", type: "file" },
      { name: "vsprintf_chk.c", desc: "安全可变参数格式化输出", type: "file" }
    ]
  },
  {
    name: "stdio (144)",
    type: "folder",
    children: [
      { name: "asiprintf.c", desc: "格式化输出到字符串", type: "file" },
      { name: "asniprintf.c", desc: "格式化输出到字符串", type: "file" },
      { name: "asnprintf.c", desc: "格式化输出到字符串", type: "file" },
      { name: "asprintf.c", desc: "格式化输出到字符串", type: "file" },
      { name: "clearerr.c", desc: "清除错误标志", type: "file" },
      { name: "clearerr_u.c", desc: "清除错误标志(解锁)", type: "file" },
      { name: "diprintf.c", desc: "整数格式化输出", type: "file" },
      { name: "dprintf.c", desc: "格式化输出到文件描述符", type: "file" },
      { name: "fclose.c", desc: "关闭文件", type: "file" },
      { name: "fcloseall.c", desc: "关闭所有文件", type: "file" },
      { name: "fdopen.c", desc: "从文件描述符打开流", type: "file" },
      { name: "feof.c", desc: "检查文件结束", type: "file" },
      { name: "feof_u.c", desc: "检查文件结束(解锁)", type: "file" },
      { name: "ferror.c", desc: "检查文件错误", type: "file" },
      { name: "ferror_u.c", desc: "检查文件错误(解锁)", type: "file" },
      { name: "fflush.c", desc: "刷新流", type: "file" },
      { name: "fflush_u.c", desc: "刷新流(解锁)", type: "file" },
      { name: "fgetc.c", desc: "读取字符", type: "file" },
      { name: "fgetc_u.c", desc: "读取字符(解锁)", type: "file" },
      { name: "fgetpos.c", desc: "获取文件位置", type: "file" },
      { name: "fgets.c", desc: "读取字符串", type: "file" },
      { name: "fgets_u.c", desc: "读取字符串(解锁)", type: "file" },
      { name: "fgetwc.c", desc: "读取宽字符", type: "file" },
      { name: "fgetwc_u.c", desc: "读取宽字符(解锁)", type: "file" },
      { name: "fgetws.c", desc: "读取宽字符串", type: "file" },
      { name: "fgetws_u.c", desc: "读取宽字符串(解锁)", type: "file" },
      { name: "fileno.c", desc: "获取文件描述符", type: "file" },
      { name: "fileno_u.c", desc: "获取文件描述符(解锁)", type: "file" },
      { name: "findfp.c", desc: "查找文件指针", type: "file" },
      { name: "fiprintf.c", desc: "整数格式化输出", type: "file" },
      { name: "fiscanf.c", desc: "整数格式化输入", type: "file" },
      { name: "flags.c", desc: "文件标志", type: "file" },
      { name: "floatio.h", desc: "浮点I/O 头文件", type: "file" },
      { name: "flockfile.c", desc: "锁定文件", type: "file" },
      { name: "fmemopen.c", desc: "内存流打开", type: "file" },
      { name: "fopen.c", desc: "打开文件", type: "file" },
      { name: "fopencookie.c", desc: "自定义流打开", type: "file" },
      { name: "fprintf.c", desc: "格式化输出", type: "file" },
      { name: "fpurge.c", desc: "清除流缓冲区", type: "file" },
      { name: "fputc.c", desc: "写入字符", type: "file" },
      { name: "fputc_u.c", desc: "写入字符(解锁)", type: "file" },
      { name: "fputs.c", desc: "写入字符串", type: "file" },
      { name: "fputs_u.c", desc: "写入字符串(解锁)", type: "file" },
      { name: "fputwc.c", desc: "写入宽字符", type: "file" },
      { name: "fputwc_u.c", desc: "写入宽字符(解锁)", type: "file" },
      { name: "fputws.c", desc: "写入宽字符串", type: "file" },
      { name: "fputws_u.c", desc: "写入宽字符串(解锁)", type: "file" },
      { name: "fread.c", desc: "读取数据", type: "file" },
      { name: "fread_u.c", desc: "读取数据(解锁)", type: "file" },
      { name: "freopen.c", desc: "重新打开文件", type: "file" },
      { name: "fscanf.c", desc: "格式化输入", type: "file" },
      { name: "fseek.c", desc: "文件定位", type: "file" },
      { name: "fseeko.c", desc: "文件定位(偏移量)", type: "file" },
      { name: "fsetlocking.c", desc: "设置流锁定", type: "file" },
      { name: "fsetpos.c", desc: "设置文件位置", type: "file" },
      { name: "ftell.c", desc: "获取文件位置", type: "file" },
      { name: "ftello.c", desc: "获取文件位置(偏移量)", type: "file" },
      { name: "funlockfile.c", desc: "解锁文件", type: "file" },
      { name: "funopen.c", desc: "自定义流打开", type: "file" },
      { name: "fvwrite.c", desc: "向量写入", type: "file" },
      { name: "fvwrite.h", desc: "向量写入头文件", type: "file" },
      { name: "fwalk.c", desc: "遍历文件流", type: "file" },
      { name: "fwide.c", desc: "设置流方向", type: "file" },
      { name: "fwprintf.c", desc: "宽字符格式化输出", type: "file" },
      { name: "fwrite.c", desc: "写入数据", type: "file" },
      { name: "fwrite_u.c", desc: "写入数据(解锁)", type: "file" },
      { name: "fwscanf.c", desc: "宽字符格式化输入", type: "file" },
      { name: "getc.c", desc: "读取字符", type: "file" },
      { name: "getc_u.c", desc: "读取字符(解锁)", type: "file" },
      { name: "getchar.c", desc: "读取标准输入字符", type: "file" },
      { name: "getchar_u.c", desc: "读取标准输入字符(解锁)", type: "file" },
      { name: "getdelim.c", desc: "读取分隔符字符串", type: "file" },
      { name: "getline.c", desc: "读取行", type: "file" },
      { name: "gets.c", desc: "读取字符串", type: "file" },
      { name: "getw.c", desc: "读取字", type: "file" },
      { name: "getwc.c", desc: "读取宽字符", type: "file" },
      { name: "getwc_u.c", desc: "读取宽字符(解锁)", type: "file" },
      { name: "getwchar.c", desc: "读取标准输入宽字符", type: "file" },
      { name: "getwchar_u.c", desc: "读取标准输入宽字符(解锁)", type: "file" },
      { name: "iprintf.c", desc: "整数格式化输出", type: "file" },
      { name: "iscanf.c", desc: "整数格式化输入", type: "file" },
      { name: "local.h", desc: "本地化头文件", type: "file" },
      { name: "makebuf.c", desc: "创建缓冲区", type: "file" },
      { name: "meson.build", desc: "Meson 构建配置", type: "file" },
      { name: "mktemp.c", desc: "创建临时文件名", type: "file" },
      { name: "nano-svfprintf.c", desc: "Nano 格式化输出", type: "file" },
      { name: "nano-svfscanf.c", desc: "Nano 格式化输入", type: "file" },
      { name: "nano-vfprintf.c", desc: "Nano 可变参数格式化输出", type: "file" },
      { name: "nano-vfprintf_float.c", desc: "Nano 浮点格式化输出", type: "file" },
      { name: "nano-vfprintf_i.c", desc: "Nano 整数格式化输出", type: "file" },
      { name: "nano-vfprintf_local.h", desc: "Nano 格式化输出本地头文件", type: "file" },
      { name: "nano-vfscanf.c", desc: "Nano 可变参数格式化输入", type: "file" },
      { name: "nano-vfscanf_float.c", desc: "Nano 浮点格式化输入", type: "file" },
      { name: "nano-vfscanf_i.c", desc: "Nano 整数格式化输入", type: "file" },
      { name: "nano-vfscanf_local.h", desc: "Nano 格式化输入本地头文件", type: "file" },
      { name: "open_memstream.c", desc: "打开内存流", type: "file" },
      { name: "perror.c", desc: "打印错误信息", type: "file" },
      { name: "printf.c", desc: "格式化输出", type: "file" },
      { name: "putc.c", desc: "写入字符", type: "file" },
      { name: "putc_u.c", desc: "写入字符(解锁)", type: "file" },
      { name: "putchar.c", desc: "写入标准输出字符", type: "file" },
      { name: "putchar_u.c", desc: "写入标准输出字符(解锁)", type: "file" },
      { name: "puts.c", desc: "写入字符串", type: "file" },
      { name: "putw.c", desc: "写入字", type: "file" },
      { name: "putwc.c", desc: "写入宽字符", type: "file" },
      { name: "putwc_u.c", desc: "写入宽字符(解锁)", type: "file" },
      { name: "putwchar.c", desc: "写入标准输出宽字符", type: "file" },
      { name: "putwchar_u.c", desc: "写入标准输出宽字符(解锁)", type: "file" },
      { name: "refill.c", desc: "填充缓冲区", type: "file" },
      { name: "remove.c", desc: "删除文件", type: "file" },
      { name: "rewind.c", desc: "重置文件位置", type: "file" },
      { name: "rget.c", desc: "读取字符", type: "file" },
      { name: "scanf.c", desc: "格式化输入", type: "file" },
      { name: "sccl.c", desc: "扫描字符类", type: "file" },
      { name: "setbuf.c", desc: "设置缓冲区", type: "file" },
      { name: "setbuffer.c", desc: "设置缓冲区", type: "file" },
      { name: "setlinebuf.c", desc: "设置行缓冲", type: "file" },
      { name: "setvbuf.c", desc: "设置缓冲区", type: "file" },
      { name: "sfputs.c", desc: "安全字符串写入", type: "file" },
      { name: "sfputws.c", desc: "安全宽字符串写入", type: "file" },
      { name: "siprintf.c", desc: "整数格式化输出", type: "file" },
      { name: "siscanf.c", desc: "整数格式化输入", type: "file" },
      { name: "sniprintf.c", desc: "整数格式化输出", type: "file" },
      { name: "snprintf.c", desc: "格式化输出到字符串", type: "file" },
      { name: "sprint.c", desc: "格式化输出到字符串", type: "file" },
      { name: "sprintf.c", desc: "格式化输出到字符串", type: "file" },
      { name: "sscanf.c", desc: "从字符串格式化输入", type: "file" },
      { name: "ssprint.c", desc: "字符串格式化输出", type: "file" },
      { name: "ssputs.c", desc: "字符串写入", type: "file" },
      { name: "ssputws.c", desc: "宽字符串写入", type: "file" },
      { name: "sswprint.c", desc: "宽字符串格式化输出", type: "file" },
      { name: "stdio.c", desc: "标准I/O 实现", type: "file" },
      { name: "stdio.h", desc: "标准I/O 头文件", type: "file" },
      { name: "stdio.tex", desc: "标准I/O 文档", type: "file" },
      { name: "stdio_ext.c", desc: "扩展标准I/O", type: "file" },
      { name: "stdio_ext.h", desc: "扩展标准I/O 头文件", type: "file" },
      { name: "svfiprintf.c", desc: "安全整数格式化输出", type: "file" },
      { name: "svfiscanf.c", desc: "安全整数格式化输入", type: "file" },
      { name: "svfiwprintf.c", desc: "安全宽字符整数格式化输出", type: "file" },
      { name: "svfiwscanf.c", desc: "安全宽字符整数格式化输入", type: "file" },
      { name: "svfprintf.c", desc: "安全格式化输出", type: "file" },
      { name: "svfscanf.c", desc: "安全格式化输入", type: "file" },
      { name: "svfwprintf.c", desc: "安全宽字符格式化输出", type: "file" },
      { name: "svfwscanf.c", desc: "安全宽字符格式化输入", type: "file" },
      { name: "swprint.c", desc: "宽字符串格式化输出", type: "file" },
      { name: "swprintf.c", desc: "宽字符格式化输出", type: "file" },
      { name: "swscanf.c", desc: "宽字符格式化输入", type: "file" },
      { name: "sys", desc: "系统相关目录", type: "file" },
      { name: "tmpfile.c", desc: "创建临时文件", type: "file" },
      { name: "tmpnam.c", desc: "创建临时文件名", type: "file" },
      { name: "ungetc.c", desc: "回退字符", type: "file" },
      { name: "ungetwc.c", desc: "回退宽字符", type: "file" },
      { name: "vasiprintf.c", desc: "可变参数整数格式化输出", type: "file" },
      { name: "vasniprintf.c", desc: "可变参数整数格式化输出", type: "file" },
      { name: "vasnprintf.c", desc: "可变参数格式化输出到字符串", type: "file" },
      { name: "vasprintf.c", desc: "可变参数格式化输出到字符串", type: "file" },
      { name: "vdiprintf.c", desc: "可变参数整数格式化输出", type: "file" },
      { name: "vdprintf.c", desc: "可变参数格式化输出到文件描述符", type: "file" },
      { name: "vfieeefp.h", desc: "IEEE 浮点头文件", type: "file" },
      { name: "vfiprintf.c", desc: "可变参数整数格式化输出", type: "file" },
      { name: "vfiscanf.c", desc: "可变参数整数格式化输入", type: "file" },
      { name: "vfiwprintf.c", desc: "可变参数宽字符整数格式化输出", type: "file" },
      { name: "vfiwscanf.c", desc: "可变参数宽字符整数格式化输入", type: "file" },
      { name: "vfprintf.c", desc: "可变参数格式化输出", type: "file" },
      { name: "vfscanf.c", desc: "可变参数格式化输入", type: "file" },
      { name: "vfwprintf.c", desc: "可变参数宽字符格式化输出", type: "file" },
      { name: "vfwscanf.c", desc: "可变参数宽字符格式化输入", type: "file" },
      { name: "viprintf.c", desc: "可变参数整数格式化输出", type: "file" },
      { name: "viscanf.c", desc: "可变参数整数格式化输入", type: "file" },
      { name: "vprintf.c", desc: "可变参数格式化输出", type: "file" },
      { name: "vscanf.c", desc: "可变参数格式化输入", type: "file" },
      { name: "vsiprintf.c", desc: "可变参数整数格式化输出", type: "file" },
      { name: "vsiscanf.c", desc: "可变参数整数格式化输入", type: "file" },
      { name: "vsniprintf.c", desc: "可变参数整数格式化输出", type: "file" },
      { name: "vsnprintf.c", desc: "可变参数格式化输出到字符串", type: "file" },
      { name: "vsprintf.c", desc: "可变参数格式化输出到字符串", type: "file" },
      { name: "vsscanf.c", desc: "可变参数从字符串格式化输入", type: "file" },
      { name: "vswprintf.c", desc: "可变参数宽字符格式化输出", type: "file" },
      { name: "vswscanf.c", desc: "可变参数宽字符格式化输入", type: "file" },
      { name: "vwprintf.c", desc: "可变参数宽字符格式化输出", type: "file" },
      { name: "vwscanf.c", desc: "可变参数宽字符格式化输入", type: "file" },
      { name: "wbuf.c", desc: "宽字符缓冲区", type: "file" },
      { name: "wbufw.c", desc: "宽字符缓冲区", type: "file" },
      { name: "wprintf.c", desc: "宽字符格式化输出", type: "file" },
      { name: "wscanf.c", desc: "宽字符格式化输入", type: "file" },
      { name: "wsetup.c", desc: "宽字符设置", type: "file" }
    ]
  },
  {
    name: "stdio64 (8)",
    type: "folder",
    children: [
      { name: "fdopen64.c", desc: "64 位文件描述符打开", type: "file" },
      { name: "fgetpos64.c", desc: "64 位获取文件位置", type: "file" },
      { name: "fopen64.c", desc: "64 位打开文件", type: "file" },
      { name: "freopen64.c", desc: "64 位重新打开文件", type: "file" },
      { name: "fseeko64.c", desc: "64 位文件定位", type: "file" },
      { name: "fsetpos64.c", desc: "64 位设置文件位置", type: "file" },
      { name: "ftello64.c", desc: "64 位获取文件位置", type: "file" },
      { name: "meson.build", desc: "Meson 构建配置", type: "file" },
      { name: "stdio64.c", desc: "64 位标准I/O 实现", type: "file" },
      { name: "stdio64.tex", desc: "64 位标准I/O 文档", type: "file" },
      { name: "tmpfile64.c", desc: "64 位临时文件", type: "file" }
    ]
  },
  {
    name: "stdlib (103)",
    type: "folder",
    children: [
      { name: "CMakeLists.txt", desc: "CMake 构建配置文件", type: "file" },
      { name: "_Exit.c", desc: "进程终止", type: "file" },
      { name: "__atexit.c", desc: "退出处理", type: "file" },
      { name: "__call_atexit.c", desc: "调用退出处理", type: "file" },
      { name: "a64l.c", desc: "ASCII64 转换", type: "file" },
      { name: "abort.c", desc: "异常终止", type: "file" },
      { name: "abs.c", desc: "绝对值", type: "file" },
      { name: "aligned_alloc.c", desc: "对齐内存分配", type: "file" },
      { name: "arc4random.c", desc: "随机数生成", type: "file" },
      { name: "arc4random.h", desc: "随机数生成头文件", type: "file" },
      { name: "arc4random_uniform.c", desc: "均匀随机数", type: "file" },
      { name: "assert.c", desc: "断言实现", type: "file" },
      { name: "assert_func.c", desc: "断言函数", type: "file" },
      { name: "assert_no_arg.c", desc: "无参数断言", type: "file" },
      { name: "atexit.c", desc: "注册退出处理", type: "file" },
      { name: "atexit.h", desc: "退出处理头文件", type: "file" },
      { name: "atof.c", desc: "字符串转浮点数", type: "file" },
      { name: "atoff.c", desc: "字符串转浮点数", type: "file" },
      { name: "atoi.c", desc: "字符串转整数", type: "file" },
      { name: "atol.c", desc: "字符串转长整数", type: "file" },
      { name: "atoll.c", desc: "字符串转长长整数", type: "file" },
      { name: "btowc.c", desc: "字节转宽字符", type: "file" },
      { name: "chacha_private.h", desc: "ChaCha 私有头文件", type: "file" },
      { name: "cxa_atexit.c", desc: "C++退出处理", type: "file" },
      { name: "cxa_finalize.c", desc: "C++ 终止处理", type: "file" },
      { name: "div.c", desc: "整数除法", type: "file" },
      { name: "drand48.c", desc: "随机数生成", type: "file" },
      { name: "dtoa.c", desc: "浮点数转字符串", type: "file" },
      { name: "ecvtbuf.c", desc: "浮点数转字符串", type: "file" },
      { name: "efgcvt.c", desc: "浮点数转字符串", type: "file" },
      { name: "environ.c", desc: "环境变量", type: "file" },
      { name: "eprintf.c", desc: "错误打印", type: "file" },
      { name: "erand48.c", desc: "随机数生成", type: "file" },
      { name: "exit.c", desc: "进程退出", type: "file" },
      { name: "gdtoa-gethex.c", desc: "十六进制浮点数解析", type: "file" },
      { name: "gdtoa-hexnan.c", desc: "十六进制NaN 处理", type: "file" },
      { name: "gdtoa.h", desc: "浮点数转换头文件", type: "file" },
      { name: "getenv.c", desc: "获取环境变量", type: "file" },
      { name: "getenv_r.c", desc: "可重入获取环境变量", type: "file" },
      { name: "getopt.c", desc: "命令行选项解析", type: "file" },
      { name: "getsubopt.3", desc: "子选项解析手册", type: "file" },
      { name: "getsubopt.c", desc: "子选项解析", type: "file" },
      { name: "ignore_handler_s.c", desc: "忽略安全处理", type: "file" },
      { name: "imaxabs.c", desc: "最大整数绝对值", type: "file" },
      { name: "imaxdiv.c", desc: "最大整数除法", type: "file" },
      { name: "itoa.c", desc: "整数转字符串", type: "file" },
      { name: "jrand48.c", desc: "随机数生成", type: "file" },
      { name: "l64a.c", desc: "长整数转ASCII64", type: "file" },
      { name: "labs.c", desc: "长整数绝对值", type: "file" },
      { name: "lcong48.c", desc: "随机数生成器配置", type: "file" },
      { name: "ldiv.c", desc: "长整数除法", type: "file" },
      { name: "ldtoa.c", desc: "长浮点数转字符串", type: "file" },
      { name: "llabs.c", desc: "长长整数绝对值", type: "file" },
      { name: "lldiv.c", desc: "长长整数除法", type: "file" },
      { name: "local.h", desc: "本地化头文件", type: "file" },
      { name: "local_s.h", desc: "本地化安全头文件", type: "file" },
      { name: "lrand48.c", desc: "随机数生成", type: "file" },
      { name: "malloc-calloc.c", desc: "内存分配-清零", type: "file" },
      { name: "malloc-cfree.c", desc: "内存释放", type: "file" },
      { name: "malloc-free.c", desc: "内存释放", type: "file" },
      { name: "malloc-mallinfo.c", desc: "内存信息", type: "file" },
      { name: "malloc-malloc.c", desc: "内存分配", type: "file" },
      { name: "malloc-malloc_stats.c", desc: "内存统计", type: "file" },
      { name: "malloc-malloc_usable_size.c", desc: "可用内存大小", type: "file" },
      { name: "malloc-mallopt.c", desc: "内存选项", type: "file" },
      { name: "malloc-memalign.c", desc: "对齐内存分配", type: "file" },
      { name: "malloc-posix_memalign.c", desc: "POSIX 对齐内存分配", type: "file" },
      { name: "malloc-pvalloc.c", desc: "页对齐内存分配", type: "file" },
      { name: "malloc-realloc.c", desc: "内存重新分配", type: "file" },
      { name: "malloc-valloc.c", desc: "页对齐内存分配", type: "file" },
      { name: "mallocr.c", desc: "可重入内存管理", type: "file" },
      { name: "mbctype.h", desc: "多字节字符类型", type: "file" },
      { name: "mblen.c", desc: "多字节字符长度", type: "file" },
      { name: "mbrlen.c", desc: "可重入多字节字符长度", type: "file" },
      { name: "mbrtowc.c", desc: "多字节转宽字符", type: "file" },
      { name: "mbsinit.c", desc: "多字节状态初始化", type: "file" },
      { name: "mbsnrtowcs.c", desc: "多字节转宽字符(可重入)", type: "file" },
      { name: "mbsrtowcs.c", desc: "多字节转宽字符", type: "file" },
      { name: "mbstowcs.c", desc: "多字节字符串转宽字符串", type: "file" },
      { name: "mbtowc.c", desc: "多字节字符转宽字符", type: "file" },
      { name: "mbtowc_r.c", desc: "可重入多字节字符转宽字符", type: "file" },
      { name: "meson.build", desc: "Meson 构建配置", type: "file" },
      { name: "mk-sb-charsets.py", desc: "单字节字符集生成", type: "file" },
      { name: "mprec.c", desc: "多精度计算", type: "file" },
      { name: "mprec.h", desc: "多精度计算头文件", type: "file" },
      { name: "mrand48.c", desc: "随机数生成", type: "file" },
      { name: "mul_overflow.h", desc: "乘法溢出头文件", type: "file" },
      { name: "nano-calloc.c", desc: "Nano 内存分配-清零", type: "file" },
      { name: "nano-free.c", desc: "Nano 内存释放", type: "file" },
      { name: "nano-getpagesize.c", desc: "Nano 获取页大小", type: "file" },
      { name: "nano-mallinfo.c", desc: "Nano 内存信息", type: "file" },
      { name: "nano-malloc-stats.c", desc: "Nano 内存统计", type: "file" },
      { name: "nano-malloc-usable-size.c", desc: "Nano 可用内存大小", type: "file" },
      { name: "nano-malloc.c", desc: "Nano 内存分配", type: "file" },
      { name: "nano-malloc.h", desc: "Nano 内存分配头文件", type: "file" },
      { name: "nano-mallopt.c", desc: "Nano 内存选项", type: "file" },
      { name: "nano-memalign.c", desc: "Nano 对齐内存分配", type: "file" },
      { name: "nano-posix-memalign.c", desc: "Nano POSIX 对齐内存分配", type: "file" },
      { name: "nano-pvalloc.c", desc: "Nano 页对齐内存分配", type: "file" },
      { name: "nano-realloc.c", desc: "Nano 内存重新分配", type: "file" },
      { name: "nano-valloc.c", desc: "Nano 页对齐内存分配", type: "file" },
      { name: "nrand48.c", desc: "随机数生成", type: "file" },
      { name: "on_exit.c", desc: "退出处理注册", type: "file" },
      { name: "pico-atexit.c", desc: "Picolibc 退出处理", type: "file" },
      { name: "pico-cxa-atexit.c", desc: "Picolibc C++退出处理", type: "file" },
      { name: "pico-exit.c", desc: "Picolibc 进程退出", type: "file" },
      { name: "pico-exitprocs.c", desc: "Picolibc 退出处理", type: "file" },
      { name: "pico-onexit.c", desc: "Picolibc 退出处理注册", type: "file" },
      { name: "pico-onexit.h", desc: "Picolibc 退出处理头文件", type: "file" },
      { name: "putenv.c", desc: "设置环境变量", type: "file" },
      { name: "quick_exit.c", desc: "快速退出", type: "file" },
      { name: "rand.c", desc: "随机数生成", type: "file" },
      { name: "rand48.c", desc: "随机数生成", type: "file" },
      { name: "rand48.h", desc: "随机数生成头文件", type: "file" },
      { name: "rand_r.c", desc: "可重入随机数生成", type: "file" },
      { name: "random.c", desc: "随机数生成", type: "file" },
      { name: "reallocarray.c", desc: "数组内存重新分配", type: "file" },
      { name: "reallocf.c", desc: "内存重新分配", type: "file" },
      { name: "rpmatch.c", desc: "正则表达式匹配", type: "file" },
      { name: "sb_charsets.c", desc: "单字节字符集", type: "file" },
      { name: "sb_charsets.h", desc: "单字节字符集头文件", type: "file" },
      { name: "seed48.c", desc: "随机数种子", type: "file" },
      { name: "set_constraint_handler_s.c", desc: "设置约束处理", type: "file" },
      { name: "setenv.c", desc: "设置环境变量", type: "file" },
      { name: "srand.c", desc: "设置随机数种子", type: "file" },
      { name: "srand48.c", desc: "设置随机数种子", type: "file" },
      { name: "srandom.c", desc: "设置随机数种子", type: "file" },
      { name: "stdlib.tex", desc: "标准库文档", type: "file" },
      { name: "strtod.c", desc: "字符串转双精度浮点数", type: "file" },
      { name: "strtodg.c", desc: "字符串转浮点数", type: "file" },
      { name: "strtoimax.c", desc: "字符串转最大整数", type: "file" },
      { name: "strtol.c", desc: "字符串转长整数", type: "file" },
      { name: "strtold.c", desc: "字符串转长双精度浮点数", type: "file" },
      { name: "strtoll.c", desc: "字符串转长长整数", type: "file" },
      { name: "strtorx.c", desc: "字符串转十六进制", type: "file" },
      { name: "strtoul.c", desc: "字符串转无符号长整数", type: "file" },
      { name: "strtoull.c", desc: "字符串转无符号长长整数", type: "file" },
      { name: "strtoumax.c", desc: "字符串转最大无符号整数", type: "file" },
      { name: "system.c", desc: "执行系统命令", type: "file" },
      { name: "utoa.c", desc: "无符号整数转字符串", type: "file" },
      { name: "wcrtomb.c", desc: "宽字符转多字节字符", type: "file" },
      { name: "wcsnrtombs.c", desc: "宽字符串转多字节字符串", type: "file" },
      { name: "wcsrtombs.c", desc: "宽字符串转多字节字符串", type: "file" },
      { name: "wcstod.c", desc: "宽字符串转双精度浮点数", type: "file" },
      { name: "wcstoimax.c", desc: "宽字符串转最大整数", type: "file" },
      { name: "wcstol.c", desc: "宽字符串转长整数", type: "file" },
      { name: "wcstold.c", desc: "宽字符串转长双精度浮点数", type: "file" },
      { name: "wcstoll.c", desc: "宽字符串转长长整数", type: "file" },
      { name: "wcstombs.c", desc: "宽字符串转多字节字符串", type: "file" },
      { name: "wcstoul.c", desc: "宽字符串转无符号长整数", type: "file" },
      { name: "wcstoull.c", desc: "宽字符串转无符号长长整数", type: "file" },
      { name: "wcstoumax.c", desc: "宽字符串转最大无符号整数", type: "file" },
      { name: "wctob.c", desc: "宽字符转字节", type: "file" },
      { name: "wctomb.c", desc: "宽字符转多字节字符", type: "file" },
      { name: "wctomb_r.c", desc: "可重入宽字符转多字节字符", type: "file" }
    ]
  },
  {
    name: "string (86)",
    type: "folder",
    children: [
      { name: "CMakeLists.txt", desc: "CMake 构建配置文件", type: "file" },
      { name: "WIDTH-A", desc: "字符宽度定义", type: "file" },
      { name: "ambiguous.t", desc: "模糊字符测试", type: "file" },
      { name: "bcmp.c", desc: "字节比较", type: "file" },
      { name: "bcopy.c", desc: "字节复制", type: "file" },
      { name: "bzero.c", desc: "字节清零", type: "file" },
      { name: "combining.t", desc: "组合字符测试", type: "file" },
      { name: "explicit_bzero.c", desc: "显式字节清零", type: "file" },
      { name: "ffsl.c", desc: "查找第一个设置位", type: "file" },
      { name: "ffsll.c", desc: "查找第一个设置位", type: "file" },
      { name: "fls.c", desc: "查找最后设置位", type: "file" },
      { name: "flsl.c", desc: "查找最后设置位", type: "file" },
      { name: "flsll.c", desc: "查找最后设置位", type: "file" },
      { name: "gnu_basename.c", desc: "GNU 基名实现", type: "file" },
      { name: "index.c", desc: "查找字符", type: "file" },
      { name: "local.h", desc: "本地化头文件", type: "file" },
      { name: "memccpy.c", desc: "内存复制", type: "file" },
      { name: "memchr.c", desc: "内存查找字符", type: "file" },
      { name: "memcmp.c", desc: "内存比较", type: "file" },
      { name: "memcpy.c", desc: "内存复制", type: "file" },
      { name: "memcpy_s.c", desc: "安全内存复制", type: "file" },
      { name: "memmem.c", desc: "内存查找子串", type: "file" },
      { name: "memmove.c", desc: "内存移动", type: "file" },
      { name: "memmove_s.c", desc: "安全内存移动", type: "file" },
      { name: "mempcpy.c", desc: "内存复制并返回指针", type: "file" },
      { name: "memrchr.c", desc: "内存反向查找字符", type: "file" },
      { name: "memset.c", desc: "内存设置", type: "file" },
      { name: "memset_explicit.c", desc: "显式内存设置", type: "file" },
      { name: "memset_s.c", desc: "安全内存设置", type: "file" },
      { name: "meson.build", desc: "Meson 构建配置", type: "file" },
      { name: "mkunidata", desc: "Unicode 数据生成器", type: "file" },
      { name: "mkwide", desc: "宽字符生成器", type: "file" },
      { name: "mkwidthA", desc: "字符宽度生成器", type: "file" },
      { name: "rawmemchr.c", desc: "原始内存查找字符", type: "file" },
      { name: "rindex.c", desc: "反向查找字符", type: "file" },
      { name: "stpcpy.c", desc: "字符串复制并返回指针", type: "file" },
      { name: "stpncpy.c", desc: "字符串复制并返回指针", type: "file" },
      { name: "str-two-way.h", desc: "双向字符串头文件", type: "file" },
      { name: "strcasecmp.c", desc: "忽略大小写字符串比较", type: "file" },
      { name: "strcasecmp_l.c", desc: "本地化忽略大小写比较", type: "file" },
      { name: "strcasestr.c", desc: "忽略大小写子串查找", type: "file" },
      { name: "strcat.c", desc: "字符串连接", type: "file" },
      { name: "strcat_s.c", desc: "安全字符串连接", type: "file" },
      { name: "strchr.c", desc: "查找字符", type: "file" },
      { name: "strchrnul.c", desc: "查找字符或结束", type: "file" },
      { name: "strcmp.c", desc: "字符串比较", type: "file" },
      { name: "strcoll.c", desc: "本地化字符串比较", type: "file" },
      { name: "strcoll_l.c", desc: "本地化字符串比较", type: "file" },
      { name: "strcpy.c", desc: "字符串复制", type: "file" },
      { name: "strcpy_s.c", desc: "安全字符串复制", type: "file" },
      { name: "strcspn.c", desc: "计算不包含字符集的长度", type: "file" },
      { name: "strdup.c", desc: "复制字符串", type: "file" },
      { name: "strerror.c", desc: "错误信息字符串", type: "file" },
      { name: "strerror_r.c", desc: "可重入错误信息", type: "file" },
      { name: "strerror_s.c", desc: "安全错误信息", type: "file" },
      { name: "strerrorlen_s.c", desc: "安全错误信息长度", type: "file" },
      { name: "string_private.h", desc: "字符串私有头文件", type: "file" },
      { name: "strings.tex", desc: "字符串文档", type: "file" },
      { name: "strlcat.c", desc: "字符串连接(限制长度)", type: "file" },
      { name: "strlcpy.c", desc: "字符串复制(限制长度)", type: "file" },
      { name: "strlen.c", desc: "字符串长度", type: "file" },
      { name: "strlwr.c", desc: "转小写", type: "file" },
      { name: "strncasecmp.c", desc: "忽略大小写字符串比较(限制长度)", type: "file" },
      { name: "strncasecmp_l.c", desc: "本地化忽略大小写比较(限制长度)", type: "file" },
      { name: "strncat.c", desc: "字符串连接(限制长度)", type: "file" },
      { name: "strncat_s.c", desc: "安全字符串连接(限制长度)", type: "file" },
      { name: "strncmp.c", desc: "字符串比较(限制长度)", type: "file" },
      { name: "strncpy.c", desc: "字符串复制(限制长度)", type: "file" },
      { name: "strncpy_s.c", desc: "安全字符串复制(限制长度)", type: "file" },
      { name: "strndup.c", desc: "复制字符串(限制长度)", type: "file" },
      { name: "strnlen.c", desc: "字符串长度(限制长度)", type: "file" },
      { name: "strnlen_s.c", desc: "安全字符串长度", type: "file" },
      { name: "strnstr.c", desc: "子串查找(限制长度)", type: "file" },
      { name: "strpbrk.c", desc: "查找字符集", type: "file" },
      { name: "strrchr.c", desc: "反向查找字符", type: "file" },
      { name: "strsep.c", desc: "分隔字符串", type: "file" },
      { name: "strsignal.c", desc: "信号信息字符串", type: "file" },
      { name: "strspn.c", desc: "计算包含字符集的长度", type: "file" },
      { name: "strstr.c", desc: "子串查找", type: "file" },
      { name: "strtok.c", desc: "分隔字符串", type: "file" },
      { name: "strtok_r.c", desc: "可重入分隔字符串", type: "file" },
      { name: "strtok_r.h", desc: "可重入分隔字符串头文件", type: "file" },
      { name: "strupr.c", desc: "转大写", type: "file" },
      { name: "strverscmp.c", desc: "版本字符串比较", type: "file" },
      { name: "strxfrm.c", desc: "字符串转换", type: "file" },
      { name: "strxfrm_l.c", desc: "本地化字符串转换", type: "file" },
      { name: "swab.c", desc: "交换字节", type: "file" },
      { name: "timingsafe_bcmp.c", desc: "时间安全字节比较", type: "file" },
      { name: "timingsafe_memcmp.c", desc: "时间安全内存比较", type: "file" },
      { name: "uniset", desc: "Unicode 字符集", type: "file" },
      { name: "wcpcpy.c", desc: "宽字符串复制并返回指针", type: "file" },
      { name: "wcpncpy.c", desc: "宽字符串复制并返回指针", type: "file" },
      { name: "wcscasecmp.c", desc: "宽字符串忽略大小写比较", type: "file" },
      { name: "wcscasecmp_l.c", desc: "本地化宽字符串忽略大小写比较", type: "file" },
      { name: "wcscat.c", desc: "宽字符串连接", type: "file" },
      { name: "wcschr.c", desc: "宽字符串查找字符", type: "file" },
      { name: "wcscmp.c", desc: "宽字符串比较", type: "file" },
      { name: "wcscoll.c", desc: "本地化宽字符串比较", type: "file" },
      { name: "wcscoll_l.c", desc: "本地化宽字符串比较", type: "file" },
      { name: "wcscpy.c", desc: "宽字符串复制", type: "file" },
      { name: "wcscspn.c", desc: "宽字符串计算不包含字符集的长度", type: "file" },
      { name: "wcsdup.c", desc: "复制宽字符串", type: "file" },
      { name: "wcslcat.c", desc: "宽字符串连接(限制长度)", type: "file" },
      { name: "wcslcpy.c", desc: "宽字符串复制(限制长度)", type: "file" },
      { name: "wcslen.c", desc: "宽字符串长度", type: "file" },
      { name: "wcsncasecmp.c", desc: "宽字符串忽略大小写比较(限制长度)", type: "file" },
      { name: "wcsncasecmp_l.c", desc: "本地化宽字符串忽略大小写比较(限制长度)", type: "file" },
      { name: "wcsncat.c", desc: "宽字符串连接(限制长度)", type: "file" },
      { name: "wcsncmp.c", desc: "宽字符串比较(限制长度)", type: "file" },
      { name: "wcsncpy.c", desc: "宽字符串复制(限制长度)", type: "file" },
      { name: "wcsnlen.c", desc: "宽字符串长度(限制长度)", type: "file" },
      { name: "wcspbrk.c", desc: "宽字符串查找字符集", type: "file" },
      { name: "wcsrchr.c", desc: "宽字符串反向查找字符", type: "file" },
      { name: "wcsspn.c", desc: "宽字符串计算包含字符集的长度", type: "file" },
      { name: "wcsstr.c", desc: "宽字符串子串查找", type: "file" },
      { name: "wcstok.c", desc: "宽字符串分隔", type: "file" },
      { name: "wcstrings.tex", desc: "宽字符串文档", type: "file" },
      { name: "wcswidth.c", desc: "宽字符串宽度", type: "file" },
      { name: "wcsxfrm.c", desc: "宽字符串转换", type: "file" },
      { name: "wcsxfrm_l.c", desc: "本地化宽字符串转换", type: "file" },
      { name: "wcwidth.c", desc: "宽字符宽度", type: "file" },
      { name: "wide.t", desc: "宽字符测试", type: "file" },
      { name: "wmemchr.c", desc: "宽内存查找字符", type: "file" },
      { name: "wmemcmp.c", desc: "宽内存比较", type: "file" },
      { name: "wmemcpy.c", desc: "宽内存复制", type: "file" },
      { name: "wmemmove.c", desc: "宽内存移动", type: "file" },
      { name: "wmempcpy.c", desc: "宽内存复制并返回指针", type: "file" },
      { name: "wmemset.c", desc: "宽内存设置", type: "file" },
      { name: "xpg_strerror_r.c", desc: "XPG 错误信息", type: "file" }
    ]
  },
  {
    name: "time (15)",
    type: "folder",
    children: [
      { name: "CMakeLists.txt", desc: "CMake 构建配置文件", type: "file" },
      { name: "asctime.c", desc: "时间转字符串", type: "file" },
      { name: "asctime_r.c", desc: "可重入时间转字符串", type: "file" },
      { name: "clock.c", desc: "时钟时间", type: "file" },
      { name: "ctime.c", desc: "时间转字符串", type: "file" },
      { name: "ctime_r.c", desc: "可重入时间转字符串", type: "file" },
      { name: "difftime.c", desc: "时间差", type: "file" },
      { name: "gettzinfo.c", desc: "获取时区信息", type: "file" },
      { name: "gmtime.c", desc: "UTC 时间", type: "file" },
      { name: "gmtime_r.c", desc: "可重入UTC 时间", type: "file" },
      { name: "lcltime.c", desc: "本地时间", type: "file" },
      { name: "lcltime_buf.c", desc: "本地时间缓冲区", type: "file" },
      { name: "lcltime_r.c", desc: "可重入本地时间", type: "file" },
      { name: "local.h", desc: "本地化头文件", type: "file" },
      { name: "meson.build", desc: "Meson 构建配置", type: "file" },
      { name: "mktime.c", desc: "构造时间", type: "file" },
      { name: "month_lengths.c", desc: "月份长度", type: "file" },
      { name: "strftime.c", desc: "格式化时间", type: "file" },
      { name: "strptime.c", desc: "解析时间字符串", type: "file" },
      { name: "time.c", desc: "时间函数", type: "file" },
      { name: "time.tex", desc: "时间文档", type: "file" },
      { name: "tzcalc_limits.c", desc: "时区计算限制", type: "file" },
      { name: "tzset.c", desc: "设置时区", type: "file" },
      { name: "tzvars.c", desc: "时区变量", type: "file" },
      { name: "wcsftime.c", desc: "宽字符格式化时间", type: "file" }
    ]
  },
  {
    name: "tinystdio (106)",
    type: "folder",
    children: [
      { name: "CMakeLists.txt", desc: "CMake 构建配置文件", type: "file" },
      { name: "asnprintf.c", desc: "格式化输出到字符串", type: "file" },
      { name: "asprintf.c", desc: "格式化输出到字符串", type: "file" },
      { name: "atod_engine.c", desc: "ASCII 转双精度浮点数引擎", type: "file" },
      { name: "atod_ryu.c", desc: "ASCII 转双精度浮点数(Ryu)", type: "file" },
      { name: "atof_engine.c", desc: "ASCII 转浮点数引擎", type: "file" },
      { name: "atof_ryu.c", desc: "ASCII 转浮点数(Ryu)", type: "file" },
      { name: "atold_engine.c", desc: "ASCII 转长双精度浮点数引擎", type: "file" },
      { name: "atomic_load.c", desc: "原子加载", type: "file" },
      { name: "bufio.c", desc: "缓冲I/O", type: "file" },
      { name: "clearerr.c", desc: "清除错误标志", type: "file" },
      { name: "compare_exchange.c", desc: "比较交换", type: "file" },
      { name: "conv_flt.c", desc: "浮点数转换", type: "file" },
      { name: "dtoa.h", desc: "双精度浮点数转字符串头文件", type: "file" },
      { name: "dtoa_engine.c", desc: "双精度浮点数转字符串引擎", type: "file" },
      { name: "dtoa_ryu.c", desc: "双精度浮点数转字符串(Ryu)", type: "file" },
      { name: "dtox_engine.c", desc: "双精度浮点数转十六进制引擎", type: "file" },
      { name: "ecvt.c", desc: "浮点数转字符串", type: "file" },
      { name: "ecvt_r.c", desc: "可重入浮点数转字符串", type: "file" },
      { name: "ecvtf.c", desc: "浮点数转字符串", type: "file" },
      { name: "ecvtf_r.c", desc: "可重入浮点数转字符串", type: "file" },
      { name: "ecvtl.c", desc: "长浮点数转字符串", type: "file" },
      { name: "ecvtl_r.c", desc: "可重入长浮点数转字符串", type: "file" },
      { name: "exchange.c", desc: "交换", type: "file" },
      { name: "fclose.c", desc: "关闭文件", type: "file" },
      { name: "fcvt.c", desc: "浮点数转字符串", type: "file" },
      { name: "fcvt_r.c", desc: "可重入浮点数转字符串", type: "file" },
      { name: "fcvtf.c", desc: "浮点数转字符串", type: "file" },
      { name: "fcvtf_r.c", desc: "可重入浮点数转字符串", type: "file" },
      { name: "fcvtl.c", desc: "长浮点数转字符串", type: "file" },
      { name: "fcvtl_r.c", desc: "可重入长浮点数转字符串", type: "file" },
      { name: "fdevopen.c", desc: "设备文件打开", type: "file" },
      { name: "fdopen.c", desc: "从文件描述符打开流", type: "file" },
      { name: "feof.c", desc: "检查文件结束", type: "file" },
      { name: "ferror.c", desc: "检查文件错误", type: "file" },
      { name: "fflush.c", desc: "刷新流", type: "file" },
      { name: "fgetc.c", desc: "读取字符", type: "file" },
      { name: "fgetpos.c", desc: "获取文件位置", type: "file" },
      { name: "fgets.c", desc: "读取字符串", type: "file" },
      { name: "fgetwc.c", desc: "读取宽字符", type: "file" },
      { name: "fgetws.c", desc: "读取宽字符串", type: "file" },
      { name: "fileno.c", desc: "获取文件描述符", type: "file" },
      { name: "filestrget.c", desc: "文件字符串获取", type: "file" },
      { name: "filestrput.c", desc: "文件字符串写入", type: "file" },
      { name: "filestrputalloc.c", desc: "文件字符串写入分配", type: "file" },
      { name: "filewstrget.c", desc: "文件宽字符串获取", type: "file" },
      { name: "flockfile.c", desc: "锁定文件", type: "file" },
      { name: "flockfile_init.c", desc: "文件锁定初始化", type: "file" },
      { name: "fmemopen.c", desc: "内存流打开", type: "file" },
      { name: "fopen.c", desc: "打开文件", type: "file" },
      { name: "fprintf.c", desc: "格式化输出", type: "file" },
      { name: "fputc.c", desc: "写入字符", type: "file" },
      { name: "fputs.c", desc: "写入字符串", type: "file" },
      { name: "fputwc.c", desc: "写入宽字符", type: "file" },
      { name: "fputws.c", desc: "写入宽字符串", type: "file" },
      { name: "fread.c", desc: "读取数据", type: "file" },
      { name: "freopen.c", desc: "重新打开文件", type: "file" },
      { name: "fscanf.c", desc: "格式化输入", type: "file" },
      { name: "fseek.c", desc: "文件定位", type: "file" },
      { name: "fseeko.c", desc: "文件定位(偏移量)", type: "file" },
      { name: "fsetpos.c", desc: "设置文件位置", type: "file" },
      { name: "ftell.c", desc: "获取文件位置", type: "file" },
      { name: "ftello.c", desc: "获取文件位置(偏移量)", type: "file" },
      { name: "ftoa_engine.c", desc: "浮点数转ASCII 引擎", type: "file" },
      { name: "ftoa_ryu.c", desc: "浮点数转ASCII(Ryu)", type: "file" },
      { name: "ftox_engine.c", desc: "浮点数转十六进制引擎", type: "file" },
      { name: "ftrylockfile.c", desc: "尝试锁定文件", type: "file" },
      { name: "funlockfile.c", desc: "解锁文件", type: "file" },
      { name: "funopen.c", desc: "自定义流打开", type: "file" },
      { name: "fwide.c", desc: "设置流方向", type: "file" },
      { name: "fwprintf.c", desc: "宽字符格式化输出", type: "file" },
      { name: "fwrite.c", desc: "写入数据", type: "file" },
      { name: "fwscanf.c", desc: "宽字符格式化输入", type: "file" },
      { name: "gcvt.c", desc: "浮点数转字符串", type: "file" },
      { name: "gcvtf.c", desc: "浮点数转字符串", type: "file" },
      { name: "gcvtl.c", desc: "长浮点数转字符串", type: "file" },
      { name: "getchar.c", desc: "读取标准输入字符", type: "file" },
      { name: "getdelim.c", desc: "读取分隔符字符串", type: "file" },
      { name: "getline.c", desc: "读取行", type: "file" },
      { name: "gets.c", desc: "读取字符串", type: "file" },
      { name: "getwchar.c", desc: "读取标准输入宽字符", type: "file" },
      { name: "ldtoa_engine.c", desc: "长双精度浮点数转ASCII 引擎", type: "file" },
      { name: "ldtox_engine.c", desc: "长双精度浮点数转十六进制引擎", type: "file" },
      { name: "matchcaseprefix.c", desc: "匹配大小写前缀", type: "file" },
      { name: "meson.build", desc: "Meson 构建配置", type: "file" },
      { name: "mktemp.c", desc: "创建临时文件名", type: "file" },
      { name: "perror.c", desc: "打印错误信息", type: "file" },
      { name: "posixiob_stderr.c", desc: "POSIX I/O 标准错误", type: "file" },
      { name: "posixiob_stdin.c", desc: "POSIX I/O标准输入", type: "file" },
      { name: "posixiob_stdout.c", desc: "POSIX I/O 标准输出", type: "file" },
      { name: "printf.c", desc: "格式化输出", type: "file" },
      { name: "putchar.c", desc: "写入标准输出字符", type: "file" },
      { name: "puts.c", desc: "写入字符串", type: "file" },
      { name: "putwchar.c", desc: "写入标准输出宽字符", type: "file" },
      { name: "remove.c", desc: "删除文件", type: "file" },
      { name: "rewind.c", desc: "重置文件位置", type: "file" },
      { name: "ryu", desc: "Ryu 浮点数转换库", type: "file" },
      { name: "ryu_divpow2.c", desc: "Ryu 除以2 的幂", type: "file" },
      { name: "ryu_log10.c", desc: "Ryu 以10 为底的对数", type: "file" },
      { name: "ryu_log2pow5.c", desc: "Ryu 以2 为底5 的对数", type: "file" },
      { name: "ryu_pow5bits.c", desc: "Ryu 5 的位数", type: "file" },
      { name: "ryu_table.c", desc: "Ryu 查找表", type: "file" },
      { name: "ryu_umul128.c", desc: "Ryu 128 位无符号乘法", type: "file" },
      { name: "scanf.c", desc: "格式化输入", type: "file" },
      { name: "scanf_private.h", desc: "格式化输入私有头文件", type: "file" },
      { name: "setbuf.c", desc: "设置缓冲区", type: "file" },
      { name: "setbuffer.c", desc: "设置缓冲区", type: "file" },
      { name: "setlinebuf.c", desc: "设置行缓冲", type: "file" },
      { name: "setvbuf.c", desc: "设置缓冲区", type: "file" },
      { name: "sflags.c", desc: "字符串标志", type: "file" },
      { name: "snprintf.c", desc: "格式化输出到字符串", type: "file" },
      { name: "snprintfd.c", desc: "双精度格式化输出到字符串", type: "file" },
      { name: "snprintff.c", desc: "浮点数格式化输出到字符串", type: "file" },
      { name: "sprintf.c", desc: "格式化输出到字符串", type: "file" },
      { name: "sprintf_s.c", desc: "安全格式化输出到字符串", type: "file" },
      { name: "sprintfd.c", desc: "双精度格式化输出到字符串", type: "file" },
      { name: "sprintff.c", desc: "浮点数格式化输出到字符串", type: "file" },
      { name: "sscanf.c", desc: "从字符串格式化输入", type: "file" },
      { name: "stdio-bufio.h", desc: "标准I/O 缓冲头文件", type: "file" },
      { name: "stdio.h", desc: "标准I/O 头文件", type: "file" },
      { name: "stdio_private.h", desc: "标准I/O 私有头文件", type: "file" },
      { name: "strfromd.c", desc: "双精度浮点数转字符串", type: "file" },
      { name: "strfromf.c", desc: "浮点数转字符串", type: "file" },
      { name: "strfroml.c", desc: "长双精度浮点数转字符串", type: "file" },
      { name: "strtod.c", desc: "字符串转双精度浮点数", type: "file" },
      { name: "strtod_l.c", desc: "本地化字符串转双精度浮点数", type: "file" },
      { name: "strtof.c", desc: "字符串转浮点数", type: "file" },
      { name: "strtof_l.c", desc: "本地化字符串转浮点数", type: "file" },
      { name: "strtoi.h", desc: "字符串转整数头文件", type: "file" },
      { name: "strtoimax.c", desc: "字符串转最大整数", type: "file" },
      { name: "strtoimax_l.c", desc: "本地化字符串转最大整数", type: "file" },
      { name: "strtol.c", desc: "字符串转长整数", type: "file" },
      { name: "strtol_l.c", desc: "本地化字符串转长整数", type: "file" },
      { name: "strtold.c", desc: "字符串转长双精度浮点数", type: "file" },
      { name: "strtold_l.c", desc: "本地化字符串转长双精度浮点数", type: "file" },
      { name: "strtoll.c", desc: "字符串转长长整数", type: "file" },
      { name: "strtoll_l.c", desc: "本地化字符串转长长整数", type: "file" },
      { name: "strtoul.c", desc: "字符串转无符号长整数", type: "file" },
      { name: "strtoul_l.c", desc: "本地化字符串转无符号长整数", type: "file" },
      { name: "strtoull.c", desc: "字符串转无符号长长整数", type: "file" },
      { name: "strtoull_l.c", desc: "本地化字符串转无符号长长整数", type: "file" },
      { name: "strtoumax.c", desc: "字符串转最大无符号整数", type: "file" },
      { name: "strtoumax_l.c", desc: "本地化字符串转最大无符号整数", type: "file" },
      { name: "swprintf.c", desc: "宽字符格式化输出", type: "file" },
      { name: "swscanf.c", desc: "宽字符格式化输入", type: "file" },
      { name: "tmpfile.c", desc: "创建临时文件", type: "file" },
      { name: "tmpnam.c", desc: "创建临时文件名", type: "file" },
      { name: "ultoa_invert.c", desc: "无符号长整数转ASCII(反转)", type: "file" },
      { name: "ungetc.c", desc: "回退字符", type: "file" },
      { name: "ungetwc.c", desc: "回退宽字符", type: "file" },
      { name: "vasnprintf.c", desc: "可变参数格式化输出到字符串", type: "file" },
      { name: "vasprintf.c", desc: "可变参数格式化输出到字符串", type: "file" },
      { name: "vffprintf.c", desc: "可变参数浮点格式化输出", type: "file" },
      { name: "vffscanf.c", desc: "可变参数浮点格式化输入", type: "file" },
      { name: "vfiprintf.c", desc: "可变参数整数格式化输出", type: "file" },
      { name: "vfiscanf.c", desc: "可变参数整数格式化输入", type: "file" },
      { name: "vflprintf.c", desc: "可变参数长浮点格式化输出", type: "file" },
      { name: "vflscanf.c", desc: "可变参数长浮点格式化输入", type: "file" },
      { name: "vfmprintf.c", desc: "可变参数内存格式化输出", type: "file" },
      { name: "vfmscanf.c", desc: "可变参数内存格式化输入", type: "file" },
      { name: "vfprintf.c", desc: "可变参数格式化输出", type: "file" },
      { name: "vfprintf_s.c", desc: "安全可变参数格式化输出", type: "file" },
      { name: "vfscanf.c", desc: "可变参数格式化输入", type: "file" },
      { name: "vfwprintf.c", desc: "可变参数宽字符格式化输出", type: "file" },
      { name: "vfwscanf.c", desc: "可变参数宽字符格式化输入", type: "file" },
      { name: "vprintf.c", desc: "可变参数格式化输出", type: "file" },
      { name: "vscanf.c", desc: "可变参数格式化输入", type: "file" },
      { name: "vsnprintf.c", desc: "可变参数格式化输出到字符串", type: "file" },
      { name: "vsnprintf_s.c", desc: "安全可变参数格式化输出到字符串", type: "file" },
      { name: "vsprintf.c", desc: "可变参数格式化输出到字符串", type: "file" },
      { name: "vsscanf.c", desc: "可变参数从字符串格式化输入", type: "file" },
      { name: "vswprintf.c", desc: "可变参数宽字符格式化输出", type: "file" },
      { name: "vswscanf.c", desc: "可变参数宽字符格式化输入", type: "file" },
      { name: "vwprintf.c", desc: "可变参数宽字符格式化输出", type: "file" },
      { name: "vwscanf.c", desc: "可变参数宽字符格式化输入", type: "file" },
      { name: "wcstod.c", desc: "宽字符串转双精度浮点数", type: "file" },
      { name: "wcstod_l.c", desc: "本地化宽字符串转双精度浮点数", type: "file" },
      { name: "wcstof.c", desc: "宽字符串转浮点数", type: "file" },
      { name: "wcstof_l.c", desc: "本地化宽字符串转浮点数", type: "file" },
      { name: "wcstoimax.c", desc: "宽字符串转最大整数", type: "file" },
      { name: "wcstoimax_l.c", desc: "本地化宽字符串转最大整数", type: "file" },
      { name: "wcstol.c", desc: "宽字符串转长整数", type: "file" },
      { name: "wcstol_l.c", desc: "本地化宽字符串转长整数", type: "file" },
      { name: "wcstold.c", desc: "宽字符串转长双精度浮点数", type: "file" },
      { name: "wcstold_l.c", desc: "本地化宽字符串转长双精度浮点数", type: "file" },
      { name: "wcstoll.c", desc: "宽字符串转长长整数", type: "file" },
      { name: "wcstoll_l.c", desc: "本地化宽字符串转长长整数", type: "file" },
      { name: "wcstoul.c", desc: "宽字符串转无符号长整数", type: "file" },
      { name: "wcstoul_l.c", desc: "本地化宽字符串转无符号长整数", type: "file" },
      { name: "wcstoull.c", desc: "宽字符串转无符号长长整数", type: "file" },
      { name: "wcstoull_l.c", desc: "本地化宽字符串转无符号长长整数", type: "file" },
      { name: "wcstoumax.c", desc: "宽字符串转最大无符号整数", type: "file" },
      { name: "wcstoumax_l.c", desc: "本地化宽字符串转最大无符号整数", type: "file" },
      { name: "wprintf.c", desc: "宽字符格式化输出", type: "file" },
      { name: "wscanf.c", desc: "宽字符格式化输入", type: "file" }
    ]
  },
  {
    name: "ubsan (23)",
    type: "folder",
    children: [
      { name: "CMakeLists.txt", desc: "CMake 构建配置文件", type: "file" },
      { name: "meson.build", desc: "Meson 构建配置", type: "file" },
      { name: "ubsan.h", desc: "未定义行为检测头文件", type: "file" },
      { name: "ubsan_cfi_type_check_to_string.c", desc: "CFI 类型检查转字符串", type: "file" },
      { name: "ubsan_error.c", desc: "未定义行为错误", type: "file" },
      { name: "ubsan_handle_add_overflow.c", desc: "处理加法溢出", type: "file" },
      { name: "ubsan_handle_alignment_assumption.c", desc: "处理对齐假设", type: "file" },
      { name: "ubsan_handle_builtin_unreachable.c", desc: "处理不可达内置", type: "file" },
      { name: "ubsan_handle_cfi_bad_type.c", desc: "处理CFI 错误类型", type: "file" },
      { name: "ubsan_handle_cfi_check_fail.c", desc: "处理CFI 检查失败", type: "file" },
      { name: "ubsan_handle_divrem_overflow.c", desc: "处理除法溢出", type: "file" },
      { name: "ubsan_handle_dynamic_type_cache_miss.c", desc: "处理动态类型缓存未命中", type: "file" },
      { name: "ubsan_handle_float_cast_overflow.c", desc: "处理浮点转换溢出", type: "file" },
      { name: "ubsan_handle_function_type_mismatch.c", desc: "处理函数类型不匹配", type: "file" },
      { name: "ubsan_handle_implicit_conversion.c", desc: "处理隐式转换", type: "file" },
      { name: "ubsan_handle_invalid_builtin.c", desc: "处理无效内置", type: "file" },
      { name: "ubsan_handle_invalid_objc_cast.c", desc: "处理无效Objective-C 转换", type: "file" },
      { name: "ubsan_handle_load_invalid_value.c", desc: "处理加载无效值", type: "file" },
      { name: "ubsan_handle_missing_return.c", desc: "处理缺少返回", type: "file" },
      { name: "ubsan_handle_mul_overflow.c", desc: "处理乘法溢出", type: "file" },
      { name: "ubsan_handle_negate_overflow.c", desc: "处理取反溢出", type: "file" },
      { name: "ubsan_handle_nonnull_arg.c", desc: "处理非空参数", type: "file" },
      { name: "ubsan_handle_nonnull_return.c", desc: "处理非空返回", type: "file" },
      { name: "ubsan_handle_nonnull_return_v1.c", desc: "处理非空返回v1", type: "file" },
      { name: "ubsan_handle_nullability_arg.c", desc: "处理可空参数", type: "file" },
      { name: "ubsan_handle_nullability_return.c", desc: "处理可空返回", type: "file" },
      { name: "ubsan_handle_nullability_return_v1.c", desc: "处理可空返回v1", type: "file" },
      { name: "ubsan_handle_out_of_bounds.c", desc: "处理越界", type: "file" },
      { name: "ubsan_handle_pointer_overflow.c", desc: "处理指针溢出", type: "file" },
      { name: "ubsan_handle_shift_out_of_bounds.c", desc: "处理移位越界", type: "file" },
      { name: "ubsan_handle_sub_overflow.c", desc: "处理减法溢出", type: "file" },
      { name: "ubsan_handle_type_mismatch.c", desc: "处理类型不匹配", type: "file" },
      { name: "ubsan_handle_type_mismatch_v1.c", desc: "处理类型不匹配v1", type: "file" },
      { name: "ubsan_handle_vla_bound_not_positive.c", desc: "处理VLA 边界非正", type: "file" },
      { name: "ubsan_message.c", desc: "未定义行为消息", type: "file" },
      { name: "ubsan_type_check_to_string.c", desc: "类型检查转字符串", type: "file" },
      { name: "ubsan_val_to_imax.c", desc: "值转最大整数", type: "file" },
      { name: "ubsan_val_to_string.c", desc: "值转字符串", type: "file" },
      { name: "ubsan_val_to_umax.c", desc: "值转最大无符号整数", type: "file" },
      { name: "ubsan_warning.c", desc: "未定义行为警告", type: "file" }
    ]
  },
  {
    name: "uchar (8)",
    type: "folder",
    children: [
      { name: "CMakeLists.txt", desc: "CMake 构建配置文件", type: "file" },
      { name: "c16rtomb.c", desc: "16 位Unicode 字符转多字节", type: "file" },
      { name: "c32rtomb.c", desc: "32 位Unicode 字符转多字节", type: "file" },
      { name: "c8rtomb.c", desc: "8 位Unicode 字符转多字节", type: "file" },
      { name: "mbrtoc16.c", desc: "多字节转16 位Unicode 字符", type: "file" },
      { name: "mbrtoc32.c", desc: "多字节转32 位Unicode 字符", type: "file" },
      { name: "mbrtoc8.c", desc: "多字节转8 位Unicode 字符", type: "file" },
      { name: "meson.build", desc: "Meson 构建配置", type: "file" },
      { name: "uchar-local.h", desc: "Unicode 字符本地头文件", type: "file" }
    ]
  },
  {
    name: "xdr (11)",
    type: "folder",
    children: [
      { name: "CMakeLists.txt", desc: "CMake 构建配置文件", type: "file" },
      { name: "README", desc: "XDR 说明文档", type: "file" },
      { name: "meson.build", desc: "Meson 构建配置", type: "file" },
      { name: "xdr.c", desc: "XDR 实现", type: "file" },
      { name: "xdr_array.c", desc: "XDR 数组处理", type: "file" },
      { name: "xdr_float.c", desc: "XDR 浮点数处理", type: "file" },
      { name: "xdr_float_vax.c", desc: "VAX 浮点数XDR处理", type: "file" },
      { name: "xdr_mem.c", desc: "XDR 内存处理", type: "file" },
      { name: "xdr_private.c", desc: "XDR 私有实现", type: "file" },
      { name: "xdr_private.h", desc: "XDR 私有头文件", type: "file" },
      { name: "xdr_rec.c", desc: "XDR 记录处理", type: "file" },
      { name: "xdr_reference.c", desc: "XDR 引用处理", type: "file" },
      { name: "xdr_sizeof.c", desc: "XDR 大小计算", type: "file" },
      { name: "xdr_stdio.c", desc: "XDR 标准I/O 处理", type: "file" }
    ]
  }
];
